### ISSUE TITLE
some inssues about usearch

### ISSUE THREAD

**Issue by Ashring-Tang** [nedialkova-lab/mim-tRNAseq#11]
Hi, sorry to  bother you again. I try to analysis the sample data you upload in the supplements. The ’PermissionError: [Errno 13] Permission denied: 'usearch' ‘ comes up as follows.
+------------------------+
| Beginning SNP indexing |
+------------------------+
2021-06-01 11:37:07,344 [INFO ] 622 total tRNA gene sequences (undetermined and nmt sequences excluded)
2021-06-01 11:37:07,344 [INFO ] 65 sequences with a match to Modomics dataset
2021-06-01 11:37:07,347 [INFO ] **** Clustering tRNA sequences ****
2021-06-01 11:37:07,348 [INFO ] Clustering tRNA sequences by 95% similarity...
Traceback (most recent call last):
  File "/root/anaconda3/2/envs/mimseq/bin/mimseq", line 10, in <module>
    sys.exit(main())
  File "/root/anaconda3/2/envs/mimseq/lib/python3.7/site-packages/mimseq/mimseq.py", line 361, in main
    args.misinc_thresh, args.mito, args.pretrnas, args.local_mod, args.sampledata)
  File "/root/anaconda3/2/envs/mimseq/lib/python3.7/site-packages/mimseq/mimseq.py", line 89, in mimseq
    = modsToSNPIndex(trnas, trnaout, mito_trnas, modifications, name, out, double_cca, snp_tolerance, cluster, cluster_id, posttrans, pretrnas, local_mod)
  File "/root/anaconda3/2/envs/mimseq/lib/python3.7/site-packages/mimseq/tRNAtools.py", line 429, in modsToSNPIndex
    subprocess.check_call(cluster_cmd, stdout = subprocess.DEVNULL, stderr=subprocess.DEVNULL)
  File "/root/anaconda3/2/envs/mimseq/lib/python3.7/subprocess.py", line 358, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/root/anaconda3/2/envs/mimseq/lib/python3.7/subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/root/anaconda3/2/envs/mimseq/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/root/anaconda3/2/envs/mimseq/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'usearch' .

I still can not sovle the above error after a few attempts.  So I ask you for help. I appreciate your helping !

**Comment by drewjbeh** [comment]
Hi

This is an error specific for the server/computer you are running mimseq on and the way usearch was installed here. There seems to be a problem with permissions so that you cannot run the usearch executable from your user. Confirm this by running `usearch` from the command line and you should get the same/similar error. 
In this case you need to contact the person who installed usearch on the server you are using to give you permissions for the usearch executable. Or download the usearch executable yourself, put it somewhere you have access to, and add this directory to your PATH.
