### ISSUE TITLE
mimseq testing error: No such file or directory: 'cmalign'

### ISSUE THREAD

**Issue by yc-2000** [nedialkova-lab/mim-tRNAseq#12]
Hi,

I tried to test the installation with the demo data but I ran into this error. I suspected it having to do with broken files but after re-installation of mimseq the issue still persists.

Here is what my command was like:
mimseq --species Hsap38 --cluster-id 0.95 --threads 4 --min-cov 2000 --max-mismatches 0.1 --control-condition HEK293T -n hg38_test --out-dir hg38_HEK239vsK562 --max-multi 4 --remap --remap-mismatches 0.075 sampledata.txt

here is the error message:

2021-06-01 12:29:20,394 [INFO ] mim-tRNAseq v0.3.4.1 run with command:
2021-06-01 12:29:20,394 [INFO ] /home/chenbvy/anaconda3/bin/mimseq --species Hsap38 --cluster-id 0.95 --threads 4 --min-cov 2000 --max-mismatches 0.1 --control-condition HEK293T -n hg38_test --out-dir hg38_HEK239vsK562 --max-multi 4 --remap --remap-mismatches 0.075 sampledata.txt
2021-06-01 12:29:20,407 [INFO ] 
+----------------------------------------------+		
| Starting analysis for hg38-tRNAs-filtered.fa |		
+----------------------------------------------+
2021-06-01 12:29:20,407 [INFO ] Processing tRNA sequences...
2021-06-01 12:29:20,439 [INFO ] 34 introns registered...
2021-06-01 12:29:20,469 [INFO ] 600 cytosolic and 22 mitochondrial tRNA sequences imported
2021-06-01 12:29:20,469 [INFO ] Processing modomics database...
2021-06-01 12:29:24,324 [INFO ] Modomics retrieved...
2021-06-01 12:29:24,325 [INFO ] Parsing Modomics JSON data...
2021-06-01 12:29:24,338 [INFO ] Number of Modomics entries for Homo sapiens: 45
2021-06-01 12:29:24,338 [INFO ] Number of Modomics entries for Escherichia coli: 43
Traceback (most recent call last):
  File "/home/chenbvy/anaconda3/bin/mimseq", line 8, in <module>
    sys.exit(main())
  File "/home/chenbvy/anaconda3/lib/python3.8/site-packages/mimseq/mimseq.py", line 358, in main
    mimseq(args.trnas, args.trnaout, args.name, args.species, args.out, args.cluster, args.cluster_id, args.cov_diff, \
  File "/home/chenbvy/anaconda3/lib/python3.8/site-packages/mimseq/mimseq.py", line 89, in mimseq
    = modsToSNPIndex(trnas, trnaout, mito_trnas, modifications, name, out, double_cca, snp_tolerance, cluster, cluster_id, posttrans, pretrnas, local_mod)
  File "/home/chenbvy/anaconda3/lib/python3.8/site-packages/mimseq/tRNAtools.py", line 261, in modsToSNPIndex
    aligntRNA(tempSeqs.name, out_dir)
  File "/home/chenbvy/anaconda3/lib/python3.8/site-packages/mimseq/ssAlign.py", line 19, in aligntRNA
    subprocess.check_call(cmcommand, stdout = open(out + 'cm.log', 'w'))
  File "/home/chenbvy/anaconda3/lib/python3.8/subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/home/chenbvy/anaconda3/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/chenbvy/anaconda3/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/chenbvy/anaconda3/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'cmalign'

Thanks in advance!

**Comment by yc-2000** [comment]
Never mind. It seems like some dependencies are not auto-installed with the mimseq
