### ISSUE TITLE
OSError: [Errno 8] Exec format error: 'usearch'

### ISSUE THREAD

**Issue by Ashring-Tang** [nedialkova-lab/mim-tRNAseq#13]
Hi, Sorry to bother you again, when begin SNP indexing,the following error comes up.Would you like to give me some guidance, I greatly appreciated to your help.
+------------------------+
| Beginning SNP indexing |
+------------------------+

2021-06-09 14:53:27,214 [INFO ] 622 total tRNA gene sequences (undetermined and nmt sequences excluded)
2021-06-09 14:53:27,215 [INFO ] 65 sequences with a match to Modomics dataset
2021-06-09 14:53:27,219 [INFO ] **** Clustering tRNA sequences ****
2021-06-09 14:53:27,219 [INFO ] Clustering tRNA sequences by 95% similarity...
Traceback (most recent call last):
  File "/root/anaconda3/2/envs/mimseq/bin/mimseq", line 10, in <module>
    sys.exit(main())
  File "/root/anaconda3/2/envs/mimseq/lib/python3.7/site-packages/mimseq/mimseq.py", line 361, in main
    args.misinc_thresh, args.mito, args.pretrnas, args.local_mod, args.sampledata)
  File "/root/anaconda3/2/envs/mimseq/lib/python3.7/site-packages/mimseq/mimseq.py", line 89, in mimseq
    = modsToSNPIndex(trnas, trnaout, mito_trnas, modifications, name, out, double_cca, snp_tolerance, cluster, cluster_id, posttrans, pretrnas, local_mod)
  File "/root/anaconda3/2/envs/mimseq/lib/python3.7/site-packages/mimseq/tRNAtools.py", line 429, in modsToSNPIndex
    subprocess.check_call(cluster_cmd, stdout = subprocess.DEVNULL, stderr=subprocess.DEVNULL)
  File "/root/anaconda3/2/envs/mimseq/lib/python3.7/subprocess.py", line 358, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/root/anaconda3/2/envs/mimseq/lib/python3.7/subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/root/anaconda3/2/envs/mimseq/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/root/anaconda3/2/envs/mimseq/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: 'usearch'

**Comment by drewjbeh** [comment]
Hi,
It appears you have not installed usearch properly. Please ensure the usearch binary is executable by running `usearch` from the command line. You should get some info about the program an no errors. In case you cannot execute the usearch command, you may need to add permissions for execution with `chmod +x /path/to/usearch` or something similar (replace `/path/to/usearch` with the path where you installed the usearch binary)
