### ISSUE TITLE
splitClusters.py 'KeyError sequence' error while running sample data

### ISSUE THREAD

**Issue by cyken6621** [nedialkova-lab/mim-tRNAseq#15]
I am running the sample data and having the following error.

$ mimseq --species Hsap38 --cluster-id 0.95 --threads 15 --min-cov 2000 --max-mismatches 0.1 --control-condition HEK293T -n hg38_test --out-dir hg38_HEK239vsK562 --max-multi 4 --remap --remap-mismatches 0.075 mim.txt
           _                 _   ____  _   _    _
 _ __ ___ (_)_ __ ___       | |_|  _ \| \ | |  / \   ___  ___  __ _
| '_ ` _ \| | '_ ` _ \ _____| __| |_) |  \| | / _ \ / __|/ _ \/ _` |
| | | | | | | | | | | |_____| |_|  _ <| |\  |/ ___ \\__ \  __/ (_| |
|_| |_| |_|_|_| |_| |_|      \__|_| \_\_| \_/_/   \_\___/\___|\__, |
                                                                 |_|

 Modification-induced misincorporation analysis of tRNA sequencing data

2021-06-23 15:07:08,078 [INFO ] mim-tRNAseq v0.3.4.1 run with command:
2021-06-23 15:07:08,078 [INFO ] /home/yk/.local/bin/mimseq --species Hsap38 --cluster-id 0.95 --threads 15 --min-cov 2000 --max-mismatches 0.1 --control-condition HEK293T -n hg38_test --out-dir hg38_HEK239vsK562 --max-multi 4 --remap --remap-mismatches 0.075 mim.txt
2021-06-23 15:07:08,079 [INFO ]
+----------------------------------------------+
| Starting analysis for hg38-tRNAs-filtered.fa |
+----------------------------------------------+
2021-06-23 15:07:08,079 [INFO ] Processing tRNA sequences...
2021-06-23 15:07:08,091 [INFO ] 34 introns registered...
2021-06-23 15:07:08,098 [INFO ] 600 cytosolic and 22 mitochondrial tRNA sequences imported
2021-06-23 15:07:08,098 [INFO ] Processing modomics database...
2021-06-23 15:07:12,093 [INFO ] Modomics retrieved...
2021-06-23 15:07:12,094 [INFO ] Parsing Modomics JSON data...
2021-06-23 15:07:12,100 [INFO ] Number of Modomics entries for Escherichia coli: 43
2021-06-23 15:07:12,100 [INFO ] Number of Modomics entries for Homo sapiens: 45
2021-06-23 15:07:48,202 [INFO ]
+------------------------+
| Beginning SNP indexing |
+------------------------+
2021-06-23 15:08:09,566 [INFO ] 622 total tRNA gene sequences (undetermined and nmt sequences excluded)
2021-06-23 15:08:09,567 [INFO ] 65 sequences with a match to Modomics dataset
2021-06-23 15:08:09,571 [INFO ] **** Clustering tRNA sequences ****
2021-06-23 15:08:09,571 [INFO ] Clustering tRNA sequences by 95% similarity...
2021-06-23 15:08:28,336 [INFO ] 286 clusters created from 622 tRNA sequences
2021-06-23 15:08:28,340 [INFO ] 295 modifications written to SNP index
2021-06-23 15:08:28,340 [INFO ] 38 A to G replacements in reference sequences for inosine modifications
2021-06-23 15:08:28,364 [INFO ]
+--------------------------+
| Generating GSNAP indices |
+--------------------------+
2021-06-23 15:08:49,436 [INFO ] Genome indices done...
2021-06-23 15:09:07,676 [INFO ] SNP indices done...
2021-06-23 15:09:07,677 [INFO ]
+-----------+
| Alignment |
+-----------+
2021-06-23 15:09:07,677 [INFO ] **** mimseq_hek_1.fastq.gz ****
2021-06-23 15:09:07,678 [INFO ] Aligning reads to Hsap38_tRNAgenome...
2021-06-23 15:09:30,917 [INFO ] Compressing SAM files, sorting, and computing mapping stats...
[bam_sort_core] merging from 0 files and 15 in-memory blocks...
2021-06-23 15:09:39,239 [INFO ] **** mimseq_hek_2.fastq.gz ****
2021-06-23 15:09:39,240 [INFO ] Aligning reads to Hsap38_tRNAgenome...
2021-06-23 15:10:03,457 [INFO ] Compressing SAM files, sorting, and computing mapping stats...
[bam_sort_core] merging from 0 files and 15 in-memory blocks...
2021-06-23 15:10:12,464 [INFO ] **** mimseq_k562_1.fastq.gz ****
2021-06-23 15:10:12,465 [INFO ] Aligning reads to Hsap38_tRNAgenome...
2021-06-23 15:10:36,521 [INFO ] Compressing SAM files, sorting, and computing mapping stats...
[bam_sort_core] merging from 0 files and 15 in-memory blocks...
2021-06-23 15:10:45,009 [INFO ] **** mimseq_k562_2.fastq.gz ****
2021-06-23 15:10:45,010 [INFO ] Aligning reads to Hsap38_tRNAgenome...
2021-06-23 15:11:08,095 [INFO ] Compressing SAM files, sorting, and computing mapping stats...
[bam_sort_core] merging from 0 files and 15 in-memory blocks...
2021-06-23 15:11:16,687 [INFO ] Alignment statistics and plot saved to hg38_HEK239vsK562/align/mapping_stats.txt
2021-06-23 15:11:16,688 [INFO ]
+------------------------------------------------------------------------------+
| Characterizing cluster mismatches for read splitting by unique tRNA sequence |
+------------------------------------------------------------------------------+
2021-06-23 15:11:16,688 [INFO ] ** Assessing mismatches between cluster members and parent... **
Traceback (most recent call last):
  File "/home/yk/.local/bin/mimseq", line 11, in <module>
    sys.exit(main())
  File "/home/yk/.local/lib/python3.6/site-packages/mimseq/mimseq.py", line 361, in main
    args.misinc_thresh, args.mito, args.pretrnas, args.local_mod, args.sampledata)
  File "/home/yk/.local/lib/python3.6/site-packages/mimseq/mimseq.py", line 104, in mimseq
    unique_isodecoderMMs, splitBool, isodecoder_sizes = splitIsodecoder(cluster_perPos_mismatchMembers, insert_dict, del_dict, tRNA_dict, cluster_dict2, out, name)
  File "/home/yk/.local/lib/python3.6/site-packages/mimseq/splitClusters.py", line 196, in splitIsodecoder
    isodecoder_sizes[isodecoder[0]] = len([info['sequence'].upper() for tRNA, info in tRNA_dict.items() if info['sequence'].upper() == tRNA_dict[isodecoder[0]]['sequence'].upper()])
  File "/home/yk/.local/lib/python3.6/site-packages/mimseq/splitClusters.py", line 196, in <listcomp>
    isodecoder_sizes[isodecoder[0]] = len([info['sequence'].upper() for tRNA, info in tRNA_dict.items() if info['sequence'].upper() == tRNA_dict[isodecoder[0]]['sequence'].upper()])
KeyError: 'sequence'

**Comment by drewjbeh** [comment]
Hi @cyken6621 
Thanks for logging this issue. This is strange indeed. I assume you are using the four fastq files from the github repo as is (that it, you haven't changed them in any way)?
I also see your sample data text file is called `mim.txt` which I guess you made yourself? Any reason you are not using the [sampleData_HEKvsK562.txt](https://github.com/nedialkova-lab/mim-tRNAseq/blob/master/sampleData_HEKvsK562.txt) that is supplied for the sample data in the repo? 
In any case, perhaps you can send me the `mim.txt` file you are using so I can try recreate this error on my side and debug. Thanks!

**Comment by cyken6621** [comment]
Hi,
Thanks for replying. I didn't change the sample data (the 4 fastq.gz). 
The  mim.txt  is also same as the sampleData_HEKvsK562.txt.  I just copy and paste the lines and save it into a shorter file name.

**Comment by drewjbeh** [comment]
I'm unable to recreate this error, which is strange. I tried making an environment with your version of python (I'm running 3.6.10, but we have multiple users using >3.7 and this works as well).
Can I suggest that your remove the environment you are currently using (if at all), and recreate a new one as per the instructions [here](https://mim-trnaseq.readthedocs.io/en/latest/start.html). This way we can at least rule out some strange environment related issue.

**Comment by cyken6621** [comment]
> I'm unable to recreate this error, which is strange. I tried making an environment with your version of python and it still worked (I usual run python 3.6.10, but we have multiple users using >3.7 and this works as well).
> Can I suggest that you remove the environment you are currently using (if at all), and recreate a new one as per the instructions [here](https://mim-trnaseq.readthedocs.io/en/latest/start.html). This way we can at least rule out some strange environment related issue.

Thank you for the reply. I have tried to use conda to reinstall mimseq. Also, download all the sample data again.
But the problem is still the same.

(mimseq) $ conda --version
conda 4.10.1
(mimseq) $ python --version
Python 3.7.10
(mimseq) $ R --version
R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

I am wondering if you can provide the MD5 information of the sample data (the 4 fastq.gz).

**Comment by drewjbeh** [comment]
I am still unable to recreate this error unfortunately so it is very difficult to debug this. It still appears that your environment is not set up correctly as your version of R is incorrect according to the package specifications. 
I don't think it has anything to do with the sample data but here are the MD5 sums for the fastq files anyway:

448751ff58595f250aca21d67afe4282  mimseq_hek_1.fastq.gz
1e33f1399a2a8aba97f11eb01c00509c  mimseq_hek_2.fastq.gz
0218df6a14afec5c36536daa1f8d9b85  mimseq_k562_1.fastq.gz
d0c658c50332ecc2ee38e65217883b4b  mimseq_k562_2.fastq.gz

**Comment by cyken6621** [comment]
Thank you for the MD5 info, I have confirmed that I am using the correct fastq.gz files.

I have tried to install the lower version of R (3.6.1) and ggplot2 (3.2.1).
However, I still have the same issue.

Then,
I tried to modify the option of "species" from Hsap38 to Hsap

$mimseq --species Hsap --cluster-id 0.95 --threads 15 --min-cov 2000 --max-mismatches 0.1 --control-condition HEK293T -n hg38_test --out-dir hg38_HEK239vsK562 --max-multi 4 --remap --remap-mismatches 0.075 mim.txt
 
This time it works just fine, without error.....

Currently, I am planning to analyze mouse tRNAs, and it works also fine (--species Mmus).

I wonder what's the difference between Hsap38 and Hsap ? 
If I want to analyze human tRNAs, which is more appropriate ?

**Comment by drewjbeh** [comment]
That is very interesting. Hsap38 uses the hg38 genome build info. from gtRNAdb, whereas Hsap uses the older hg19 human genome version.
Hsap38 has been working fine for us for some time now. I wonder if there is some slight difference between Hsap and Hsap38 that is somehow an issue on your system. I will look into this. Ideally, you would use Hsap38 for human data as it is the newer more updated genome verison.
Thanks for troubleshooting this and finding the issue!
