### ISSUE TITLE
IndexError: Too many levels: Index has only 1 level, not 2

### ISSUE THREAD

**Issue by Ashring-Tang** [nedialkova-lab/mim-tRNAseq#16]
hi，
Sorry to bother you，
       Now I can successful get the out files with the 'sampledata' you submitted in the paper with your help. Then I try to analysis my own data ,but the following error occurred. Would you give me some suggestion? I appreciate for your help. 

+---------------------------------------------------------------------------------+        
| Determining un-deconvoluted clusters due to insufficient coverage at mismatches |        
+---------------------------------------------------------------------------------+
2021-06-30 16:45:40,651 [INFO ] *** Un-deconvoluted sequences being defined based on coverage difference more than 0.5
2021-06-30 16:45:40,651 [INFO ] Determining unsplittable sequences...
2021-06-30 16:45:40,662 [INFO ] Calculating nucleotide coverage for hg38_ALK-0630-2/mimseq_alk-_1.unpaired_uniq.bam
2021-06-30 16:45:40,663 [INFO ] Calculating nucleotide coverage for hg38_ALK-0630-2/mimseq_alk-_2.unpaired_uniq.bam
2021-06-30 16:45:40,663 [INFO ] Calculating nucleotide coverage for hg38_ALK-0630-2/mimseq_alk+_1.unpaired_uniq.bam
2021-06-30 16:45:40,664 [INFO ] Calculating nucleotide coverage for hg38_ALK-0630-2/mimseq_alk+_2.unpaired_uniq.bam
2021-06-30 16:45:41,369 [INFO ] 0 unique sequences excluded from deconvolution due to reductions in required coverage at mismatches of more than 50.00%
2021-06-30 16:45:41,370 [INFO ] 
+--------------------------------------------------------------------+		
| Analysing misincorporations and stops to RT, and analysing 3' ends |		
+--------------------------------------------------------------------+
2021-06-30 16:45:41,370 [WARNI] Rewriting over old mods and CCA files...
2021-06-30 16:45:41,550 [INFO ] Analysing hg38_ALK-0630-2/mimseq_alk-_1.unpaired_uniq.bam...
2021-06-30 16:45:41,551 [INFO ] Analysing hg38_ALK-0630-2/mimseq_alk-_2.unpaired_uniq.bam...
2021-06-30 16:45:41,556 [INFO ] Analysing hg38_ALK-0630-2/mimseq_alk+_1.unpaired_uniq.bam...
2021-06-30 16:45:41,558 [INFO ] Analysing hg38_ALK-0630-2/mimseq_alk+_2.unpaired_uniq.bam...
2021-06-30 16:45:41,559 [INFO ] Finding potential unannotated mods for hg38_ALK-0630-2/mimseq_alk-_1.unpaired_uniq.bam
2021-06-30 16:45:41,559 [INFO ] Building modification, stop and count data tables for hg38_ALK-0630-2/mimseq_alk-_1.unpaired_uniq.bam
2021-06-30 16:45:41,561 [INFO ] Finding potential unannotated mods for hg38_ALK-0630-2/mimseq_alk-_2.unpaired_uniq.bam
2021-06-30 16:45:41,561 [INFO ] Building modification, stop and count data tables for hg38_ALK-0630-2/mimseq_alk-_2.unpaired_uniq.bam
2021-06-30 16:45:41,564 [INFO ] Finding potential unannotated mods for hg38_ALK-0630-2/mimseq_alk+_1.unpaired_uniq.bam
2021-06-30 16:45:41,564 [INFO ] Building modification, stop and count data tables for hg38_ALK-0630-2/mimseq_alk+_1.unpaired_uniq.bam
2021-06-30 16:45:41,566 [INFO ] Finding potential unannotated mods for hg38_ALK-0630-2/mimseq_alk+_2.unpaired_uniq.bam
2021-06-30 16:45:41,567 [INFO ] Building modification, stop and count data tables for hg38_ALK-0630-2/mimseq_alk+_2.unpaired_uniq.bam
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/root/anaconda3/envs/mimseq/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/root/anaconda3/envs/mimseq/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/root/anaconda3/envs/mimseq/lib/python3.7/site-packages/mimseq/mmQuant.py", line 286, in bamMods_mp
    modTable_prop_melt = modTable_prop_df.melt(id_vars=['type'], var_name=['isodecoder','pos'], value_name='proportion')
  File "/root/anaconda3/envs/mimseq/lib/python3.7/site-packages/pandas/core/frame.py", line 7374, in melt
    ignore_index=ignore_index,
  File "/root/anaconda3/envs/mimseq/lib/python3.7/site-packages/pandas/core/reshape/melt.py", line 131, in melt
    mdata[col] = np.asanyarray(frame.columns._get_level_values(i)).repeat(N)
  File "/root/anaconda3/envs/mimseq/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 1556, in _get_level_values
    self._validate_index_level(level)
  File "/root/anaconda3/envs/mimseq/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 1476, in _validate_index_level
    f"Too many levels: Index has only 1 level, not {level + 1}"
IndexError: Too many levels: Index has only 1 level, not 2
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/envs/mimseq/bin/mimseq", line 10, in <module>
    sys.exit(main())
  File "/root/anaconda3/envs/mimseq/lib/python3.7/site-packages/mimseq/mimseq.py", line 361, in main
    args.misinc_thresh, args.mito, args.pretrnas, args.local_mod, args.sampledata)
  File "/root/anaconda3/envs/mimseq/lib/python3.7/site-packages/mimseq/mimseq.py", line 135, in mimseq
    new_mods, new_Inosines, filtered_cov, filter_warning = generateModsTable(coverageData, out, name, threads, min_cov, mismatch_dict, insert_dict, del_dict, cluster_dict, cca, remap, misinc_thresh, new_mod_lists, Inosine_lists, newtRNA_dict, Inosine_clusters, unique_isodecoderMMs, newSplitBool, isodecoder_sizes, cluster)
  File "/root/anaconda3/envs/mimseq/lib/python3.7/site-packages/mimseq/mmQuant.py", line 598, in generateModsTable
    new_mods, new_Inosines = zip(*pool.map(func, bamlist))
  File "/root/anaconda3/envs/mimseq/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/root/anaconda3/envs/mimseq/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
IndexError: Too many levels: Index has only 1 level, not 2

**Comment by drewjbeh** [comment]
Hi there,
Could you please send the full log file which is located in the output folder. It is called something like `mim-tRNAseq_H-M-S.log` where H-M-S is the time in hours, minutes, seconds. Additionally, could you also send me the `mapping_stats.txt` file.

Please also check which version of pandas you are using. You can do this by following the instructions below:
1. Make sure you are in the mimseq environment and then start the python interpreter by typing `python`
2. `import pandas`
3. Check version with `pandas.__version__`

**Comment by Ashring-Tang** [comment]
hi，
I will try as the instructions you provided. Also send you the two files, it seems that the reads mapping reads is not well.  Thanks for your help again.


















At 2021-06-30 17:12:27, "Drew Behrens" ***@***.***> wrote:

Hi there,
Could you please send the full log file which is located in the output folder. It is called something like mim-tRNAseq_H-M-S.log where H-M-S is the time in hours, minutes, seconds. Additionally, could you also send me the mapping_stats.txt file.

Please also check which version of pandas you are using. You can do this by following the instructions below:

Make sure you are in the mimseq environment and then start the python interpreter by typing python
import pandas
Check version with pandas.__version__

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
2021-06-30 15:22:47,505 [INFO ] mim-tRNAseq v0.3.4.1 run with command:
2021-06-30 15:22:47,505 [INFO ] /root/anaconda3/envs/mimseq/bin/mimseq --species Hsap38 --cluster-id 0.95 --threads 15 --min-cov 2000 --max-mismatches 0.1 --control-condition ALK- -n hg38_test --out-dir hg38_ALK --max-multi 4 --remap --remap-mismatches 0.075 sampledata_alk-vsalk+.txt --misinc-thresh 1
2021-06-30 15:22:47,505 [INFO ] 
+----------------------------------------------+		
| Starting analysis for hg38-tRNAs-filtered.fa |		
+----------------------------------------------+
2021-06-30 15:22:47,505 [INFO ] Processing tRNA sequences...
2021-06-30 15:22:47,512 [INFO ] 34 introns registered...
2021-06-30 15:22:47,517 [INFO ] 600 cytosolic and 22 mitochondrial tRNA sequences imported
2021-06-30 15:22:47,517 [INFO ] Processing modomics database...
2021-06-30 15:22:52,734 [INFO ] Modomics retrieved...
2021-06-30 15:22:52,735 [INFO ] Parsing Modomics JSON data...
2021-06-30 15:22:52,744 [INFO ] Number of Modomics entries for Escherichia coli: 43
2021-06-30 15:22:52,744 [INFO ] Number of Modomics entries for Homo sapiens: 45
2021-06-30 15:22:59,651 [INFO ] 
+------------------------+ 		
| Beginning SNP indexing |		
+------------------------+
2021-06-30 15:34:52,908 [INFO ] 622 total tRNA gene sequences (undetermined and nmt sequences excluded)
2021-06-30 15:34:52,909 [INFO ] 65 sequences with a match to Modomics dataset
2021-06-30 15:34:52,916 [INFO ] **** Clustering tRNA sequences ****
2021-06-30 15:34:52,916 [INFO ] Clustering tRNA sequences by 95% similarity...
2021-06-30 15:34:57,731 [INFO ] 287 clusters created from 622 tRNA sequences
2021-06-30 15:34:57,734 [INFO ] 292 modifications written to SNP index
2021-06-30 15:34:57,734 [INFO ] 43 A to G replacements in reference sequences for inosine modifications
2021-06-30 15:34:57,745 [INFO ] 
+--------------------------+ 		 
| Generating GSNAP indices |		 
+--------------------------+
2021-06-30 15:35:19,082 [INFO ] Genome indices done...
2021-06-30 15:35:34,861 [INFO ] SNP indices done...
2021-06-30 15:35:34,861 [INFO ] 
+-----------+ 			
| Alignment |			
+-----------+
2021-06-30 15:35:34,862 [INFO ] **** mimseq_alk-_1.fastq.gz ****
2021-06-30 15:35:34,863 [INFO ] Aligning reads to Hsap38_tRNAgenome...
2021-06-30 15:36:48,249 [INFO ] Compressing SAM files, sorting, and computing mapping stats...
2021-06-30 15:36:54,282 [INFO ] **** mimseq_alk-_2.fastq.gz ****
2021-06-30 15:36:54,282 [INFO ] Aligning reads to Hsap38_tRNAgenome...
2021-06-30 15:38:10,796 [INFO ] Compressing SAM files, sorting, and computing mapping stats...
2021-06-30 15:38:17,389 [INFO ] **** mimseq_alk+_1.fastq.gz ****
2021-06-30 15:38:17,389 [INFO ] Aligning reads to Hsap38_tRNAgenome...
2021-06-30 15:38:53,370 [INFO ] Compressing SAM files, sorting, and computing mapping stats...
2021-06-30 15:38:56,168 [INFO ] **** mimseq_alk+_2.fastq.gz ****
2021-06-30 15:38:56,168 [INFO ] Aligning reads to Hsap38_tRNAgenome...
2021-06-30 15:39:34,294 [INFO ] Compressing SAM files, sorting, and computing mapping stats...
2021-06-30 15:39:38,049 [INFO ] Alignment statistics and plot saved to hg38_ALK/align/mapping_stats.txt
2021-06-30 15:39:38,050 [INFO ] 
+------------------------------------------------------------------------------+        
| Characterizing cluster mismatches for read splitting by unique tRNA sequence |       
+------------------------------------------------------------------------------+
2021-06-30 15:39:38,050 [INFO ] ** Assessing mismatches between cluster members and parent... **
2021-06-30 15:39:38,091 [INFO ] Total unique sequences: 436
2021-06-30 15:39:38,091 [INFO ] Single sequence clusters: 217
2021-06-30 15:39:38,092 [INFO ] Deconvoluted sequences: 219
2021-06-30 15:39:38,092 [INFO ] Total deconvoluted sequences 436
2021-06-30 15:39:43,094 [INFO ] 
+---------------------------------------------------------------------------------+        
| Determining un-deconvoluted clusters due to insufficient coverage at mismatches |        
+---------------------------------------------------------------------------------+
2021-06-30 15:39:43,094 [INFO ] *** Un-deconvoluted sequences being defined based on coverage difference more than 0.5
2021-06-30 15:39:43,095 [INFO ] Determining unsplittable sequences...
2021-06-30 15:39:43,153 [INFO ] Calculating nucleotide coverage for hg38_ALK/mimseq_alk-_2.unpaired_uniq.bam
2021-06-30 15:39:43,153 [INFO ] Calculating nucleotide coverage for hg38_ALK/mimseq_alk-_1.unpaired_uniq.bam
2021-06-30 15:39:43,155 [INFO ] Calculating nucleotide coverage for hg38_ALK/mimseq_alk+_1.unpaired_uniq.bam
2021-06-30 15:39:43,156 [INFO ] Calculating nucleotide coverage for hg38_ALK/mimseq_alk+_2.unpaired_uniq.bam
2021-06-30 15:39:43,860 [INFO ] 0 unique sequences excluded from deconvolution due to reductions in required coverage at mismatches of more than 50.00%
2021-06-30 15:39:43,860 [INFO ] 
+--------------------------------------------------------------------+		
| Analysing misincorporations and stops to RT, and analysing 3' ends |		
+--------------------------------------------------------------------+
2021-06-30 15:39:43,861 [INFO ] ** Discovering unannotated modifications for realignment **
2021-06-30 15:39:44,042 [INFO ] Analysing hg38_ALK/mimseq_alk-_1.unpaired_uniq.bam...
2021-06-30 15:39:44,046 [INFO ] Analysing hg38_ALK/mimseq_alk-_2.unpaired_uniq.bam...
2021-06-30 15:39:44,049 [INFO ] Analysing hg38_ALK/mimseq_alk+_1.unpaired_uniq.bam...
2021-06-30 15:39:44,053 [INFO ] Finding potential unannotated mods for hg38_ALK/mimseq_alk-_1.unpaired_uniq.bam
2021-06-30 15:39:44,054 [INFO ] Analysis complete for hg38_ALK/mimseq_alk-_1.unpaired_uniq.bam...
2021-06-30 15:39:44,054 [INFO ] Finding potential unannotated mods for hg38_ALK/mimseq_alk-_2.unpaired_uniq.bam
2021-06-30 15:39:44,055 [INFO ] Analysis complete for hg38_ALK/mimseq_alk-_2.unpaired_uniq.bam...
2021-06-30 15:39:44,056 [INFO ] Analysing hg38_ALK/mimseq_alk+_2.unpaired_uniq.bam...
2021-06-30 15:39:44,058 [INFO ] Finding potential unannotated mods for hg38_ALK/mimseq_alk+_1.unpaired_uniq.bam
2021-06-30 15:39:44,058 [INFO ] Analysis complete for hg38_ALK/mimseq_alk+_1.unpaired_uniq.bam...
2021-06-30 15:39:44,064 [INFO ] Finding potential unannotated mods for hg38_ALK/mimseq_alk+_2.unpaired_uniq.bam
2021-06-30 15:39:44,064 [INFO ] Analysis complete for hg38_ALK/mimseq_alk+_2.unpaired_uniq.bam...
2021-06-30 15:39:44,130 [INFO ] 
+------------------+ 		
| Parsing new mods |		
+------------------+
2021-06-30 15:39:44,130 [INFO ] 0 new predicted position 34 inosines
2021-06-30 15:39:44,130 [INFO ] 0 new predicted modifications
2021-06-30 15:39:44,139 [INFO ] 249 modifications written to SNP index
2021-06-30 15:39:44,140 [INFO ] 
+----------------------------+ 		
| Regenerating GSNAP indices |		
+----------------------------+
2021-06-30 15:39:44,140 [WARNI] Genome index folder found! Rebuilding index anyway...
2021-06-30 15:40:05,535 [INFO ] Genome indices done...
2021-06-30 15:40:05,536 [WARNI] SNP index folder found! Rebuilding index anyway...
2021-06-30 15:40:21,954 [INFO ] SNP indices done...
2021-06-30 15:40:21,955 [INFO ] 
+------------------+ 			
| Realigning reads |			
+------------------+
2021-06-30 15:40:21,955 [INFO ] **** mimseq_alk-_1.fastq.gz ****
2021-06-30 15:40:21,956 [INFO ] Aligning reads to Hsap38_tRNAgenome...
2021-06-30 15:41:35,590 [INFO ] Compressing SAM files, sorting, and computing mapping stats...
2021-06-30 15:41:41,675 [INFO ] **** mimseq_alk-_2.fastq.gz ****
2021-06-30 15:41:41,675 [INFO ] Aligning reads to Hsap38_tRNAgenome...
2021-06-30 15:42:58,311 [INFO ] Compressing SAM files, sorting, and computing mapping stats...
2021-06-30 15:43:05,025 [INFO ] **** mimseq_alk+_1.fastq.gz ****
2021-06-30 15:43:05,026 [INFO ] Aligning reads to Hsap38_tRNAgenome...
2021-06-30 15:43:40,085 [INFO ] Compressing SAM files, sorting, and computing mapping stats...
2021-06-30 15:43:44,288 [INFO ] **** mimseq_alk+_2.fastq.gz ****
2021-06-30 15:43:44,289 [INFO ] Aligning reads to Hsap38_tRNAgenome...
2021-06-30 15:44:22,596 [INFO ] Compressing SAM files, sorting, and computing mapping stats...
2021-06-30 15:44:26,348 [INFO ] Alignment statistics and plot saved to hg38_ALK/align/mapping_stats.txt
2021-06-30 15:44:26,349 [INFO ] 
+---------------------------------------------------------------------------------+        
| Determining un-deconvoluted clusters due to insufficient coverage at mismatches |        
+---------------------------------------------------------------------------------+
2021-06-30 15:44:26,349 [INFO ] *** Un-deconvoluted sequences being defined based on coverage difference more than 0.5
2021-06-30 15:44:26,349 [INFO ] Determining unsplittable sequences...
2021-06-30 15:44:26,360 [INFO ] Calculating nucleotide coverage for hg38_ALK/mimseq_alk-_1.unpaired_uniq.bam
2021-06-30 15:44:26,360 [INFO ] Calculating nucleotide coverage for hg38_ALK/mimseq_alk-_2.unpaired_uniq.bam
2021-06-30 15:44:26,360 [INFO ] Calculating nucleotide coverage for hg38_ALK/mimseq_alk+_1.unpaired_uniq.bam
2021-06-30 15:44:26,361 [INFO ] Calculating nucleotide coverage for hg38_ALK/mimseq_alk+_2.unpaired_uniq.bam
2021-06-30 15:44:26,965 [INFO ] 0 unique sequences excluded from deconvolution due to reductions in required coverage at mismatches of more than 50.00%
2021-06-30 15:44:26,965 [INFO ] 
+--------------------------------------------------------------------+		
| Analysing misincorporations and stops to RT, and analysing 3' ends |		
+--------------------------------------------------------------------+
2021-06-30 15:44:26,965 [WARNI] Rewriting over old mods and CCA files...
2021-06-30 15:44:27,141 [INFO ] Analysing hg38_ALK/mimseq_alk-_1.unpaired_uniq.bam...
2021-06-30 15:44:27,147 [INFO ] Analysing hg38_ALK/mimseq_alk-_2.unpaired_uniq.bam...
2021-06-30 15:44:27,150 [INFO ] Analysing hg38_ALK/mimseq_alk+_1.unpaired_uniq.bam...
2021-06-30 15:44:27,152 [INFO ] Finding potential unannotated mods for hg38_ALK/mimseq_alk-_1.unpaired_uniq.bam
2021-06-30 15:44:27,152 [INFO ] Building modification, stop and count data tables for hg38_ALK/mimseq_alk-_1.unpaired_uniq.bam
2021-06-30 15:44:27,153 [INFO ] Analysing hg38_ALK/mimseq_alk+_2.unpaired_uniq.bam...
2021-06-30 15:44:27,155 [INFO ] Finding potential unannotated mods for hg38_ALK/mimseq_alk-_2.unpaired_uniq.bam
2021-06-30 15:44:27,156 [INFO ] Building modification, stop and count data tables for hg38_ALK/mimseq_alk-_2.unpaired_uniq.bam
2021-06-30 15:44:27,159 [INFO ] Finding potential unannotated mods for hg38_ALK/mimseq_alk+_1.unpaired_uniq.bam
2021-06-30 15:44:27,159 [INFO ] Building modification, stop and count data tables for hg38_ALK/mimseq_alk+_1.unpaired_uniq.bam
2021-06-30 15:44:27,164 [INFO ] Finding potential unannotated mods for hg38_ALK/mimseq_alk+_2.unpaired_uniq.bam
2021-06-30 15:44:27,164 [INFO ] Building modification, stop and count data tables for hg38_ALK/mimseq_alk+_2.unpaired_uniq.bam

mimseq_alk-_1.fastq.gz
Uniquely mapped reads: 0 (0%) 
Multi-mapping reads: 0 (0%) 
Unmapped reads: 14818653 (100%) 
Total: 14818653

mimseq_alk-_2.fastq.gz
Uniquely mapped reads: 0 (0%) 
Multi-mapping reads: 0 (0%) 
Unmapped reads: 14818653 (100%) 
Total: 14818653

mimseq_alk+_1.fastq.gz
Uniquely mapped reads: 0 (0%) 
Multi-mapping reads: 0 (0%) 
Unmapped reads: 8007574 (100%) 
Total: 8007574

mimseq_alk+_2.fastq.gz
Uniquely mapped reads: 0 (0%) 
Multi-mapping reads: 0 (0%) 
Unmapped reads: 8007574 (100%) 
Total: 8007574

** NEW ALIGNMENT **

mimseq_alk-_1.fastq.gz
Uniquely mapped reads: 0 (0%) 
Multi-mapping reads: 0 (0%) 
Unmapped reads: 14818653 (100%) 
Total: 14818653

** NEW ALIGNMENT **

mimseq_alk-_2.fastq.gz
Uniquely mapped reads: 0 (0%) 
Multi-mapping reads: 0 (0%) 
Unmapped reads: 14818653 (100%) 
Total: 14818653

** NEW ALIGNMENT **

mimseq_alk+_1.fastq.gz
Uniquely mapped reads: 0 (0%) 
Multi-mapping reads: 0 (0%) 
Unmapped reads: 8007574 (100%) 
Total: 8007574

** NEW ALIGNMENT **

mimseq_alk+_2.fastq.gz
Uniquely mapped reads: 0 (0%) 
Multi-mapping reads: 0 (0%) 
Unmapped reads: 8007574 (100%) 
Total: 8007574

**Comment by drewjbeh** [comment]
Yes, the problem is certainly with the alignment! I would ensure that your reads have been trimmed according to the adapters you used during library generation. This is often the most common cause of bad alignment.
I also noticed that your fastq files labeled "1" and "2" for each condition seem to have exactly the same number of reads. Are these forward and reverse reads from paired-end sequencing experiment? If so, please note that mimseq supports only single-end sequencing data currently and so your data might not be suitable for mimseq analysis.

**Comment by cyken6621** [comment]
I have the same experience that I put the untrimmed raw reads into mimseq and got the same error.
After trimming of the adapter sequences, it worked just fine.
Hope this helps.

**Comment by drewjbeh** [comment]
@cyken6621 thanks for your input!
