### ISSUE TITLE
Problems with gmap_build

### ISSUE THREAD

**Issue by MKoesters** [nedialkova-lab/mim-tRNAseq#19]
Hi,

while trying to install the software using conda, I ran into another problem.

Following the README, I executed the foloowing commands:

```
conda create -n mimseq python=3.7
conda activate mimseq
conda config --add channels conda-forge
conda install -c conda-forge mamba
mamba install -c bioconda mimseq
```

Everything worked until that, however executing 
`mimseq --species Hsap19 --cluster-id 0.95 --threads 15 --min-cov 2000 --max-mismatches 0.1 --control-condition HEK293T -n hg38_test --out-dir hg38_HEK239vsK562 --max-multi 4 --remap --remap-mismatches 0.075 sampleData_HEKvsK562.txt`
fails due to `gmap_build`

```
           _                 _   ____  _   _    _                   
 _ __ ___ (_)_ __ ___       | |_|  _ \| \ | |  / \   ___  ___  __ _ 
| '_ ` _ \| | '_ ` _ \ _____| __| |_) |  \| | / _ \ / __|/ _ \/ _` |
| | | | | | | | | | | |_____| |_|  _ <| |\  |/ ___ \\__ \  __/ (_| |
|_| |_| |_|_|_| |_| |_|      \__|_| \_\_| \_/_/   \_\___/\___|\__, |
                                                                 |_|

 Modification-induced misincorporation analysis of tRNA sequencing data

2021-08-23 13:07:00,353 [INFO ] mim-tRNAseq v0.3.4.3 run with command:
2021-08-23 13:07:00,353 [INFO ] /home/leon/.conda/envs/mimseq/bin/mimseq --species Hsap19 --cluster-id 0.95 --threads 15 --min-cov 2000 --max-mismatches 0.1 --control-condition HEK293T -n hg38_test --out-dir hg38_HEK239vsK562 --max-multi 4 --remap --remap-mismatches 0.075 sampleData_HEKvsK562.txt
2021-08-23 13:07:00,354 [INFO ] 
+---------------------------------------+		
| Starting analysis for hg19_eColitK.fa |		
+---------------------------------------+
2021-08-23 13:07:00,354 [INFO ] Processing tRNA sequences...
2021-08-23 13:07:00,361 [INFO ] 34 introns registered...
2021-08-23 13:07:00,366 [INFO ] 574 cytosolic and 22 mitochondrial tRNA sequences imported
2021-08-23 13:07:00,366 [INFO ] Processing modomics database...
2021-08-23 13:07:03,073 [INFO ] Modomics retrieved...
2021-08-23 13:07:03,073 [INFO ] Parsing Modomics JSON data...
2021-08-23 13:07:03,076 [INFO ] Number of Modomics entries for Escherichia coli: 43
2021-08-23 13:07:03,076 [INFO ] Number of Modomics entries for Homo sapiens: 45
2021-08-23 13:07:10,131 [INFO ] 
+------------------------+ 		
| Beginning SNP indexing |		
+------------------------+
2021-08-23 13:11:25,925 [INFO ] 596 total tRNA gene sequences (undetermined and nmt sequences excluded)
2021-08-23 13:11:25,925 [INFO ] 60 sequences with a match to Modomics dataset
2021-08-23 13:11:25,928 [INFO ] **** Clustering tRNA sequences ****
2021-08-23 13:11:25,928 [INFO ] Clustering tRNA sequences by 95% similarity...
2021-08-23 13:11:30,536 [INFO ] 273 clusters created from 596 tRNA sequences
2021-08-23 13:11:30,539 [INFO ] 283 modifications/cluster mismatches written to SNP index
2021-08-23 13:11:30,539 [INFO ] 40 A to G replacements in reference sequences for inosine modifications
2021-08-23 13:11:30,571 [INFO ] 
+--------------------------+ 		
| Generating GSNAP indices |		
+--------------------------+
Traceback (most recent call last):
  File "/home/leon/.conda/envs/mimseq/bin/mimseq", line 10, in <module>
    sys.exit(main())
  File "/home/leon/.conda/envs/mimseq/lib/python3.7/site-packages/mimseq/mimseq.py", line 369, in main
    args.misinc_thresh, args.mito, args.pretrnas, args.local_mod, args.p_adj, args.sampledata)
  File "/home/leon/.conda/envs/mimseq/lib/python3.7/site-packages/mimseq/mimseq.py", line 92, in mimseq
    genome_index_path, genome_index_name, snp_index_path, snp_index_name = generateGSNAPIndices(species, name, out, map_round, snp_tolerance, cluster)
  File "/home/leon/.conda/envs/mimseq/lib/python3.7/site-packages/mimseq/tRNAtools.py", line 830, in generateGSNAPIndices
    subprocess.check_call(index_cmd, stderr = open(out_dir + "genomeindex.log", "w"), stdout = subprocess.DEVNULL) 
  File "/home/leon/.conda/envs/mimseq/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gmap_build', '-q', '1', '-D', 'hg38_HEK239vsK562/', '-d', 'Hsap19_tRNAgenome', 'hg38_HEK239vsK562/hg38_test_clusterTranscripts.fa']' returned non-zero exit status 13.
```

Executing `gmap_build` in my terminal results in: 

```
Can't locate warnings.pm:   /root/perl5/lib/perl5/warnings.pm: Permission denied at /home/leon/.conda/envs/mimseq/bin/gmap_build line 4.
BEGIN failed--compilation aborted at /home/leon/.conda/envs/mimseq/bin/gmap_build line 4.
```

First I wonder if its correct that warnings should be installed to root and seconds, ` /root/perl5/lib/perl5/warnings.pm` does not seem to be there, as well as other required perl packages

Do you have an explanation for this?

**Comment by drewjbeh** [comment]
Hi there,

This seems to be an issue with your perl installation. In my mimseq environment, typing `which perl` shows me that the perl binary is located in the binary directory of my environment - `/home/drew/anaconda3/envs/mimseq/bin/perl`. I was also able to locate the `warnings.pm` file in `/home/drew/anaconda3/envs/mimseq/lib/5.26.2/`. Yours should be something similar. Perhaps you could try reinstalling perl in the environment?
