### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'name'

### ISSUE THREAD

**Issue by Pablolo99** [nedialkova-lab/mim-tRNAseq#23]
Hello
Im trying to use mimseq to analize A.thaliana data. To do so, I got the fasta file and out file of the tRNA of this organism from GtRNAdb . There is not data from plastids tRNA, such as chloroplastics, in these files, so I added that data obtained from our previous study and running tRNAscan, obtaining  in the same format as it is required to run mimseq. In the process to run it, it appears this error message ' AttributeError: 'DataFrame' object has no attribute 'name' ' . I tested to run the program only with the chromosome data (the provided from GtRNAdb) and there is no problem, and using only the data of plastid tRNA and it shows the error, so the problem must be in these sequences. The problem is that i can not see why the program doesnt work correctly if the sequences have the same format, can you give me a hint? Here I post the process until it gaves error and I attach you the files used to run mimseq.

> +-----------+ 			
| Alignment |			
+-----------+
2021-11-22 12:17:49,776 [INFO ] **** S1882Nr19.1_trimmed.fq.gz ****
2021-11-22 12:17:49,776 [INFO ] Aligning reads to araTha1-tRNAaddition_tRNAgenome...
2021-11-22 12:25:00,229 [INFO ] Compressing SAM files, sorting, and computing mapping stats...
[bam_sort_core] merging from 15 files and 15 in-memory blocks...
2021-11-22 12:26:52,638 [INFO ] **** S1882Nr20.1_trimmed.fq.gz ****
2021-11-22 12:26:52,639 [INFO ] Aligning reads to araTha1-tRNAaddition_tRNAgenome...
2021-11-22 12:33:49,744 [INFO ] Compressing SAM files, sorting, and computing mapping stats...
[bam_sort_core] merging from 15 files and 15 in-memory blocks...
2021-11-22 12:35:44,271 [INFO ] Alignment statistics and plot saved to /home/piotr/projects/results/Athalia_mimseqtest12allsame2/align/mapping_stats.txt
2021-11-22 12:35:44,272 [INFO ] 
+------------------------------------------------------------------------------+        
| Characterizing cluster mismatches for read splitting by unique tRNA sequence |       
+------------------------------------------------------------------------------+
2021-11-22 12:35:44,273 [INFO ] ** Assessing mismatches between cluster members and parent... **
2021-11-22 12:35:44,350 [INFO ] Total unique sequences: 219
2021-11-22 12:35:44,351 [INFO ] Single sequence clusters: 74
2021-11-22 12:35:44,351 [INFO ] Deconvoluted sequences: 145
2021-11-22 12:35:44,351 [INFO ] Total deconvoluted sequences 219
2021-11-22 12:35:50,694 [INFO ] 
+---------------------------------------------------------------------------------+        
| Determining un-deconvoluted clusters due to insufficient coverage at mismatches |        
+---------------------------------------------------------------------------------+
2021-11-22 12:35:50,694 [INFO ] *** Un-deconvoluted sequences being defined based on coverage difference more than 0.5
2021-11-22 12:35:50,695 [INFO ] Determining unsplittable sequences...
2021-11-22 12:35:50,760 [INFO ] Calculating nucleotide coverage for /home/piotr/projects/results/Athalia_mimseqtest12allsame2/S1882Nr19.1_trimmed.fq.gz.unpaired_uniq.bam
2021-11-22 12:35:50,761 [INFO ] Calculating nucleotide coverage for /home/piotr/projects/results/Athalia_mimseqtest12allsame2/S1882Nr20.1_trimmed.fq.gz.unpaired_uniq.bam
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/piotr/anaconda3/envs/mimseq/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/piotr/anaconda3/envs/mimseq/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/piotr/anaconda3/envs/mimseq/lib/python3.7/site-packages/mimseq/splitClusters.py", line 261, in covCheck_mp
    end = max(cov_df.loc[cov_df.name == cluster,'thickStart'])
  File "/home/piotr/anaconda3/envs/mimseq/lib/python3.7/site-packages/pandas/core/generic.py", line 5478, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'name'
"""
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/piotr/anaconda3/envs/mimseq/bin/mimseq", line 33, in <module>
    sys.exit(load_entry_point('mimseq==0.3.4.5', 'console_scripts', 'mimseq')())
  File "/home/piotr/anaconda3/envs/mimseq/lib/python3.7/site-packages/mimseq/mimseq.py", line 373, in main
    args.misinc_thresh, args.mito, args.pretrnas, args.local_mod, args.p_adj, args.sampledata)
  File "/home/piotr/anaconda3/envs/mimseq/lib/python3.7/site-packages/mimseq/mimseq.py", line 105, in mimseq
    unsplit = unsplitClusters(coverageData, coverage_bed, unique_isodecoderMMs, threads, cov_diff)
  File "/home/piotr/anaconda3/envs/mimseq/lib/python3.7/site-packages/mimseq/splitClusters.py", line 294, in unsplitClusters
    unsplit, unsplit_isosOnly = zip(*pool.map(func, bamlist))
  File "/home/piotr/anaconda3/envs/mimseq/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/piotr/anaconda3/envs/mimseq/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
AttributeError: 'DataFrame' object has no attribute 'name'

out file
[araTha1-tRNAaddition.fa_plastidsadd2.txt](https://github.com/nedialkova-lab/mim-tRNAseq/files/7581061/araTha1-tRNAaddition.fa_plastidsadd2.txt)

fasta file
[araTha1-tRNAaddition.out_plastidsadd2.txt](https://github.com/nedialkova-lab/mim-tRNAseq/files/7581056/araTha1-tRNAaddition.out_plastidsadd2.txt)

text file with the data to analyze: 
[Test.txt](https://github.com/nedialkova-lab/mim-tRNAseq/files/7581092/Test.txt)

The gz files to analize I will send it to your email compressed as a zip folder, because i dont know why it doesnt allow me to attach it here.

By the way, I have just tried if the same error comes using the data you provided on mimseq by default but just changing the species option for my fasta and out files, it results in 0 errors despite most of the sequences are not aligned as I expected, but no incovenients  this time.
 
The command line I write is:

>  /home/piotr/anaconda3/envs/mimseq/bin/mimseq -t /home/piotr/projects/GtRNAdb/araTha1-tRNAs/araTha1-tRNAaddition.fa_plastidsadd2 -o /home/piotr/projects/GtRNAdb/araTha1-tRNAs/araTha1-tRNAaddition.out_plastidsadd2 --cluster-id 0.95 --threads 15 --min-cov 0.0005 --max-mismatches 0.1 --control-condition W0 -n test --out-dir /home/piotr/projects/results/Athalia_mimseqtest12allsame2 --max-multi 4 --remap --remap-mismatches 0.075 Test

Im using the mimseq v0.3.4.5 with Python 3.7.11

**Comment by drewjbeh** [comment]
Hi @Pablolo99.
The problem is that mimseq expects a different file for the mitochondrial (or plastid) sequences given using `-m`. You can see all mimseq parameters using `mimseq --help`, and these options and the analysis we performed are described in detail in the manuscript (https://www.sciencedirect.com/science/article/pii/S1097276521000484) and in the documentation (https://mim-trnaseq.readthedocs.io/). In the paper you will see that we use predictions of mitochondrial tRNAs from the mitotRNAdb (http://mttrna.bioinf.uni-leipzig.de/mtDataOutput/) instead of tRNAScan-SE, and this is what mimseq expects. You can see an example of this formatting [here](https://github.com/nedialkova-lab/mim-tRNAseq/blob/master/mimseq/data/hg38-eColitK/hg38-mitotRNAs.fa). The most important things here are the format of the headers; specifically the species, three-letter amino acid, and anticodon. The other fields are not important, however they must be there (that is, the total number of fields separated by "|" is crucial), and in the same order.

**Comment by Pablolo99** [comment]
Thank you very much!
