### ISSUE TITLE
Unsupported format character

### ISSUE THREAD

**Issue by dpryan79** [nedialkova-lab/mim-tRNAseq#3]
Xref: https://github.com/bioconda/bioconda-recipes/pull/26911

FYI, the most recent version is throwing an error on bioconda due to an "unsupported format character" in what you're sending to argparse:

```
16:29:56 BIOCONDA INFO (OUT) + mimseq --help
16:29:59 BIOCONDA INFO (OUT) Traceback (most recent call last):
16:29:59 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/mimseq_1613751521548/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/mimseq", line 10, in <module>
16:29:59 BIOCONDA INFO (OUT)            _                 _   ____  _   _    _
16:29:59 BIOCONDA INFO (OUT)  _ __ ___ (_)_ __ ___       | |_|  _ \| \ | |  / \   ___  ___  __ _
16:29:59 BIOCONDA INFO (OUT) | '_ ` _ \| | '_ ` _ \ _____| __| |_) |  \| | / _ \ / __|/ _ \/ _` |
16:29:59 BIOCONDA INFO (OUT) | | | | | | | | | | | |_____| |_|  _ <| |\  |/ ___ \\__ \  __/ (_| |
16:29:59 BIOCONDA INFO (OUT) |_| |_| |_|_|_| |_| |_|      \__|_| \_\_| \_/_/   \_\___/\___|\__, |
16:29:59 BIOCONDA INFO (OUT)                                                                  |_|
16:29:59 BIOCONDA INFO (OUT) 
16:29:59 BIOCONDA INFO (OUT)  Modification-induced misincorporation analysis of tRNA sequencing data
16:29:59 BIOCONDA INFO (OUT) 
16:29:59 BIOCONDA INFO (OUT)     sys.exit(main())
16:29:59 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/mimseq_1613751521548/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.8/site-packages/mimseq/mimseq.py", line 303, in main
16:29:59 BIOCONDA INFO (OUT)     args = parser.parse_args()
16:29:59 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/mimseq_1613751521548/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.8/argparse.py", line 1768, in parse_args
16:29:59 BIOCONDA INFO (OUT)     args, argv = self.parse_known_args(args, namespace)
16:29:59 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/mimseq_1613751521548/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.8/argparse.py", line 1800, in parse_known_args
16:29:59 BIOCONDA INFO (OUT)     namespace, args = self._parse_known_args(args, namespace)
16:29:59 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/mimseq_1613751521548/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.8/argparse.py", line 2006, in _parse_known_args
16:29:59 BIOCONDA INFO (OUT)     start_index = consume_optional(start_index)
16:29:59 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/mimseq_1613751521548/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.8/argparse.py", line 1946, in consume_optional
16:29:59 BIOCONDA INFO (OUT)     take_action(action, args, option_string)
16:29:59 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/mimseq_1613751521548/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.8/argparse.py", line 1874, in take_action
16:29:59 BIOCONDA INFO (OUT)     action(self, namespace, argument_values, option_string)
16:29:59 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/mimseq_1613751521548/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.8/argparse.py", line 1044, in __call__
16:29:59 BIOCONDA INFO (OUT)     parser.print_help()
16:29:59 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/mimseq_1613751521548/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.8/argparse.py", line 2494, in print_help
16:29:59 BIOCONDA INFO (OUT)     self._print_message(self.format_help(), file)
16:29:59 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/mimseq_1613751521548/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.8/argparse.py", line 2478, in format_help
16:29:59 BIOCONDA INFO (OUT)     return formatter.format_help()
16:29:59 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/mimseq_1613751521548/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.8/argparse.py", line 282, in format_help
16:29:59 BIOCONDA INFO (OUT)     help = self._root_section.format_help()
16:29:59 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/mimseq_1613751521548/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.8/argparse.py", line 213, in format_help
16:29:59 BIOCONDA INFO (OUT)     item_help = join([func(*args) for func, args in self.items])
16:29:59 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/mimseq_1613751521548/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.8/argparse.py", line 213, in <listcomp>
16:29:59 BIOCONDA INFO (OUT)     item_help = join([func(*args) for func, args in self.items])
16:29:59 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/mimseq_1613751521548/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.8/argparse.py", line 213, in format_help
16:29:59 BIOCONDA INFO (OUT)     item_help = join([func(*args) for func, args in self.items])
16:29:59 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/mimseq_1613751521548/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.8/argparse.py", line 213, in <listcomp>
16:29:59 BIOCONDA INFO (OUT)     item_help = join([func(*args) for func, args in self.items])
16:29:59 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/mimseq_1613751521548/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.8/argparse.py", line 529, in _format_action
16:29:59 BIOCONDA INFO (OUT)     help_text = self._expand_help(action)
16:29:59 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/mimseq_1613751521548/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.8/argparse.py", line 621, in _expand_help
16:29:59 BIOCONDA INFO (OUT)     return self._get_help_string(action) % params
16:29:59 BIOCONDA INFO (OUT) ValueError: unsupported format character 'm' (0x6d) at index 40
```

**Comment by dpryan79** [comment]
Here's the cause: https://github.com/nedialkova-lab/mim-tRNAseq/commit/1ac82c185e3cb70881821175eb61379825e97d2b#diff-0860b52b9c91ddbeaf1c51028bcb55cdfd25bed9f975aaa9be692fd13d603c04R266

You wanted "%% m"

**Comment by drewjbeh** [comment]
@dpryan79 Thanks for pointing this out. Will fix and push changes.
