### ISSUE TITLE
non-zero exist status 9 error 

### ISSUE THREAD

**Issue by nepena** [nedialkova-lab/mim-tRNAseq#30]
Hello, 

I am was trying to run mimseq and got a returned non-zero exit status 9 error. I am unsure to pinpoint the cause of the error and was wondering if it is due to not enough memory available to run the program? I have attached the error file generated following sbatch submission. Thank you for your help!

Best,
Noah

```
2022-04-12 15:18:28,244 [INFO ] mim-tRNAseq v1.0.2 run with command:
2022-04-12 15:18:28,249 [INFO ] /home/npena/.conda/envs/mimseq/bin/mimseq --species Hsap --cluster-id 0.95 --threads 10 --min-cov 0.0005 --max-mismatches 0.1 --control-condition WT_control --no-cca-analysis -n hek_mods_correl --out-dir 3_mimseq_results readme_files.txt
2022-04-12 15:18:28,284 [INFO ]
+----------------------------------------------+
| Starting analysis for hg38-tRNAs-filtered.fa |
+----------------------------------------------+
2022-04-12 15:18:28,284 [INFO ] Processing tRNA sequences...
2022-04-12 15:18:28,364 [INFO ] 34 introns registered...
2022-04-12 15:18:28,373 [INFO ] 600 cytosolic and 22 mitochondrial tRNA sequences imported
2022-04-12 15:18:28,373 [INFO ] Processing modomics database...
2022-04-12 15:20:35,836 [ERROR] Error in connecting to Modomics: HTTPConnectionPool(host='www.genesilico.pl', port=80): Max retries exceeded with url: /modomics/api/sequences?&RNAtype=tRNA (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4b158b2950>: Failed to establish a new connection: [Errno 110] Connection timed out')). Using local Modomics files...
2022-04-12 15:20:35,844 [INFO ] Parsing local Modomics data...
2022-04-12 15:20:35,902 [INFO ] Number of Modomics entries for Homo sapiens: 45
2022-04-12 15:20:35,903 [INFO ] Number of Modomics entries for Escherichia coli: 43
2022-04-12 15:20:45,934 [INFO ]
+------------------------+
| Beginning SNP indexing |
+------------------------+
2022-04-12 15:21:36,719 [INFO ] 622 total tRNA gene sequences (undetermined and nmt sequences excluded)
2022-04-12 15:21:36,720 [INFO ] 60 sequences with a match to Modomics dataset
2022-04-12 15:21:36,726 [INFO ] **** Clustering tRNA sequences ****
2022-04-12 15:21:36,726 [INFO ] Clustering tRNA sequences by 95% similarity...
2022-04-12 15:21:44,869 [INFO ] 288 clusters created from 622 tRNA sequences
2022-04-12 15:21:44,874 [INFO ] 285 modifications/cluster mismatches written to SNP index
2022-04-12 15:21:44,875 [INFO ] 43 A to G replacements in reference sequences for inosine modifications
2022-04-12 15:21:44,983 [INFO ]
+--------------------------+
| Generating GSNAP indices |
+--------------------------+
2022-04-12 15:22:10,290 [INFO ] Genome indices done...
2022-04-12 15:22:32,916 [INFO ] SNP indices done...
2022-04-12 15:22:32,916 [INFO ]
+-----------+
| Alignment |
+-----------+
2022-04-12 15:22:32,918 [INFO ] **** TP-CK-16S-AW1_S1L1_bc1_TTCC.FINAL.fastq.gz ****
2022-04-12 15:22:32,918 [INFO ] Aligning reads to Hsap_tRNAgenome...
Traceback (most recent call last):
  File "/home/npena/.conda/envs/mimseq/bin/mimseq", line 10, in <module>
    sys.exit(main())
  File "/home/npena/.local/lib/python3.7/site-packages/mimseq/mimseq.py", line 405, in main
    args.misinc_thresh, args.mito, args.plant, args.pretrnas, args.local_mod, args.p_adj, args.sampledata)
  File "/home/npena/.local/lib/python3.7/site-packages/mimseq/mimseq.py", line 108, in mimseq
    snp_index_path, snp_index_name, out, threads, snp_tolerance, keep_temp, mismatches, map_round, remap)
  File "/home/npena/.local/lib/python3.7/site-packages/mimseq/tRNAmap.py", line 48, in mainAlign
    unique_bam, librarySize, alignstats = mapReads(fq, genome_index_path, genome_index_name, snp_index_path, snp_index_name, threads, out_dir, snp_tolerance, keep_temp, mismatches, remap)
  File "/home/npena/.local/lib/python3.7/site-packages/mimseq/tRNAmap.py", line 115, in mapReads
    subprocess.check_call(map_cmd, stderr = open(out_dir + "align.log", "a"))
File "/home/npena/.conda/envs/mimseq/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gsnap', '--gunzip', '-D', '3_mimseq_results/Hsap_tRNAgenome', '-d', 'Hsap_tRNAgenome', '-V', '3_mimseq_results/Hsapsnp_index', '-v', 'hek_mods_correl_modificationSNPs', '-t', '10', '--split-output', '3_mimseq_results/TP-CK-16S-AW1_S1L1_bc1_TTCC.FINAL', '--format', 'sam', '--genome-unk-mismatch', '0', '--md-lowercase-snp', '--ignore-trim-in-filtering', '1', '--max-mismatches', '0.1', './1_preprocessing/TP-CK-16S-AW1_S1L1_bc1_TTCC.FINAL.fastq.gz']' returned non-zero exit status 9.
```

**Comment by nepena** [comment]
Hello, 

So decided to check the align.log and saw that the program was unable to open the file. The reason? Because the name is incorrect within the txt file that contains the PATH and treatment_name. So if you get 'returned non-zero exit status 9', likely means that the program was unable to open the file and PATH for the files should be double checked! 

Hope to save someone a few hours of googling. 

Best,
Noah

**Comment by drewjbeh** [comment]
Hi Noah,

Great that you were able to find and fix the error yourself! Thanks for the useful post here for anyone else who might have this issue. I certainly have many times :)
