### ISSUE TITLE
error when install mimseq through mamba: ModuleNotFoundError: No module named 'conda._vendor.auxlib'

### ISSUE THREAD

**Issue by AiweiWu** [nedialkova-lab/mim-tRNAseq#44]
An error was reported when I install mimseq through mamba shown as bellow:
> mamba install -c bioconda mimseq
Traceback (most recent call last):
  File "/home/data/awwu/00.install/miniconda3/envs/mimseq_5/bin/mamba", line 7, in <module>
    from mamba.mamba import main
  File "/home/data/awwu/00.install/miniconda3/envs/mimseq_5/lib/python3.7/site-packages/mamba/mamba.py", line 53, in <module>
    from mamba.utils import get_index, to_package_record_from_subjson, _supplement_index_with_system
  File "/home/data/awwu/00.install/miniconda3/envs/mimseq_5/lib/python3.7/site-packages/mamba/utils.py", line 7, in <module>
    from .FastSubdirData import FastSubdirData
  File "/home/data/awwu/00.install/miniconda3/envs/mimseq_5/lib/python3.7/site-packages/mamba/FastSubdirData.py", line 23, in <module>
    from conda._vendor.auxlib.ish import dals
ModuleNotFoundError: No module named 'conda._vendor.auxlib'

conda version: 23.7.2

**Comment by drewjbeh** [comment]
Hi there,

This seems to be a conda/mamba issue and not a mimseq issue (https://github.com/mamba-org/mamba/issues/1583). I would imagine installing any other package with mamba produces the same result. 
I suggest following some of the fixes in the link above, or upgrading/reinstalling mamba. My personal suggestion is the mambaforge version of miniforge (https://github.com/conda-forge/miniforge)
