### ISSUE TITLE
Error occur when"Parsing Modomics JSON data"

### ISSUE THREAD

**Issue by wuxujia-dev** [nedialkova-lab/mim-tRNAseq#45]
Hi Behrens,

Thank you for such a useful tool!
I met an error when I testd the demo data. I used the example parameters.
mimseq --species Hsap --cluster-id 0.97 --threads 15 --min-cov 0.0005 --max-mismatches 0.075 --control-condition HEK293T -n hg38_test --out-dir hg38_HEK239vsK562 --max-multi 4 --remap --remap-mismatches 0.05 sampleData_HEKvsK562.txt

Here is what I got:

           _                 _   ____  _   _    _
 _ __ ___ (_)_ __ ___       | |_|  _ \| \ | |  / \   ___  ___  __ _
| '_ ` _ \| | '_ ` _ \ _____| __| |_) |  \| | / _ \ / __|/ _ \/ _` |
| | | | | | | | | | | |_____| |_|  _ <| |\  |/ ___ \\__ \  __/ (_| |
|_| |_| |_|_|_| |_| |_|      \__|_| \_\_| \_/_/   \_\___/\___|\__, |
                                                                 |_|

 Modification-induced misincorporation analysis of tRNA sequencing data

2023-09-21 13:17:02,070 [INFO ] mim-tRNAseq v1.3.7 run with command:
2023-09-21 13:17:02,070 [INFO ] /home/wuxujia/anaconda3/envs/mimseq/bin/mimseq --species Hsap --cluster-id 0.97 --threads 15 --min-cov 0.0005 --max-mismatches 0.075 --control-condition HEK293T -n hg38_test --out-dir hg38_HEK239vsK562 --max-multi 4 --remap --remap-mismatches 0.05 sampleData_HEKvsK562.txt
2023-09-21 13:17:02,071 [INFO ]
+-----------------------------------------+
| Starting analysis for hg38-tRNAs-all.fa |
+-----------------------------------------+
2023-09-21 13:17:02,071 [INFO ] Processing tRNA sequences...
2023-09-21 13:17:02,079 [INFO ] 34 introns registered...
2023-09-21 13:17:02,084 [INFO ] 22 mitochondrial tRNA sequences imported
2023-09-21 13:17:02,085 [INFO ] 611 filtered cytosolic tRNA sequences imported (Und, NNN and nmt sequences excluded)
2023-09-21 13:17:02,085 [INFO ] Processing modomics database...
2023-09-21 13:17:05,889 [INFO ] Modomics retrieved...
2023-09-21 13:17:05,891 [INFO ] Parsing Modomics JSON data...
Traceback (most recent call last):
  File "/home/wuxujia/anaconda3/envs/mimseq/bin/mimseq", line 10, in <module>
    sys.exit(main())
  File "/home/wuxujia/anaconda3/envs/mimseq/lib/python3.7/site-packages/mimseq/mimseq.py", line 424, in main
    args.misinc_thresh, args.mito, args.plastid, args.pretrnas, args.local_mod, args.p_adj, args.crosstalks, args.sampledata)
  File "/home/wuxujia/anaconda3/envs/mimseq/lib/python3.7/site-packages/mimseq/mimseq.py", line 102, in mimseq
    = modsToSNPIndex(trnas, trnaout, mito_trnas, plastid_trnas, modifications, name, out, double_cca, threads, snp_tolerance, cluster, cluster_id, posttrans, pretrnas, local_mod)
  File "/home/wuxujia/anaconda3/envs/mimseq/lib/python3.7/site-packages/mimseq/tRNAtools.py", line 253, in modsToSNPIndex
    tRNA_dict, modomics_dict, species = tRNAparser(gtRNAdb, tRNAscan_out, mitotRNAs, plastidtRNAs, modifications_table, posttrans_mod_off, double_cca, pretrnas, local_mod)
  File "/home/wuxujia/anaconda3/envs/mimseq/lib/python3.7/site-packages/mimseq/tRNAtools.py", line 103, in tRNAparser
    modomics_dict, perSpecies_count = processModomics(modomics_file, fetch, species, modifications)
  File "/home/wuxujia/anaconda3/envs/mimseq/lib/python3.7/site-packages/mimseq/tRNAtools.py", line 147, in processModomics
    unmod_sequence = getUnmodSeq(sequence, modifications)
  File "/home/wuxujia/anaconda3/envs/mimseq/lib/python3.7/site-packages/mimseq/tRNAtools.py", line 930, in getUnmodSeq
    char = modification_table[char]['ref']
KeyError: 'Ζ'

I removed mim-seq package and re-installed it again. This error still showed up. I tested my own data and the same thing happened. Do you have any suggestion for this error? Thank you so much.

Best wishes,
Xujia

**Comment by nedialkova-lab** [comment]
Hi Xujia - the issue comes from a recent update to MODOMICS, which included a new modification whose symbol is "Z" that is not present in the table of modifications we currently use when fetching data from there. We're working on a fix that should be available mid next week.

**Comment by wuxujia-dev** [comment]
您的邮件已收到，谢谢您的来信。

**Comment by wuxujia-dev** [comment]
Thank you so much!

**Comment by doudou0908** [comment]
Hi Behrens,
Thanks for your useful software.
when i run my data. i had this kind of error:
Traceback (most recent call last):
  File "/home/zlt/miniconda3/bin/mimseq", line 10, in <module>
    sys.exit(main())
  File "/home/zlt/miniconda3/lib/python3.9/site-packages/mimseq/mimseq.py", line 358, in main
    mimseq(args.trnas, args.trnaout, args.name, args.species, args.out, args.cluster, args.cluster_id, args.cov_diff, \
  File "/home/zlt/miniconda3/lib/python3.9/site-packages/mimseq/mimseq.py", line 89, in mimseq
    = modsToSNPIndex(trnas, trnaout, mito_trnas, modifications, name, out, double_cca, snp_tolerance, cluster, cluster_id, posttrans, pretrnas, local_mod)
  File "/home/zlt/miniconda3/lib/python3.9/site-packages/mimseq/tRNAtools.py", line 242, in modsToSNPIndex
    tRNA_dict, modomics_dict, species = tRNAparser(gtRNAdb, tRNAscan_out, mitotRNAs, modifications_table, posttrans_mod_off, double_cca, pretrnas, local_mod)
  File "/home/zlt/miniconda3/lib/python3.9/site-packages/mimseq/tRNAtools.py", line 93, in tRNAparser
    modomics_dict, perSpecies_count = processModomics(modomics_file, fetch, species, modifications)
  File "/home/zlt/miniconda3/lib/python3.9/site-packages/mimseq/tRNAtools.py", line 136, in processModomics
    unmod_sequence = getUnmodSeq(sequence, modifications)
  File "/home/zlt/miniconda3/lib/python3.9/site-packages/mimseq/tRNAtools.py", line 917, in getUnmodSeq
    char = modification_table[char]['ref']
KeyError: 'ʆ'
could you give me some suggestions?  maybe the issue also comes from the update of  MODOMICS?

thank you very much!

**Comment by nedialkova-lab** [comment]
Hi - yes, same issue with new MODOMICS symbols, working on a fix.

**Comment by xiao-yi-lshuai** [comment]
Hi Behrens, 
Thank you for providing such a useful tool. I have the same problem as "doudou0908" does. When this problem could be solved？ Thank you very much!

**Comment by wuxujia-dev** [comment]
您的邮件已收到，谢谢您的来信。

**Comment by doudou0908** [comment]
hi

I used it on Wednesday, but the error occurred again on Wednesday night.

wuxujia-dev ***@***.***>于2023年10月8日 周日14:30写道：

**Comment by nedialkova-lab** [comment]
We haven't released a fix yet - you can use the option --local modomics (see README for more info) until then.

**Comment by kelly-sovacool** [comment]
> We haven't released a fix yet - you can use the option --local modomics (see README for more info) until then.

@nedialkova-lab can you provide more details on using this --local option? I'm not sure what you're referring to in the README.

**Comment by wuxujia-dev** [comment]
您的邮件已收到，谢谢您的来信。

**Comment by kelly-sovacool** [comment]
@wuxujia-dev it appears you have an auto-reply set up that is automatically responding to new comments in this issue thread. You may wish to turn off your auto-reply for automated emails from GitHub so it doesn't clutter up issue threads that you're subscribed to.

**Comment by drewjbeh** [comment]
> > We haven't released a fix yet - you can use the option --local modomics (see README for more info) until then.
> 
> @nedialkova-lab can you provide more details on using this --local option? I'm not sure what you're referring to in the README.

The `--local-modomics` option enables mimseq to use a local downloaded version of the MODOMICS database instead of trying to connect to the MODOMICS API to retrieve that data online every time it runs. This would be ideal but the folks at MODOMICS have not updated the API to be compatible with the modification abbreviations in their tRNA sequences. Hopefully that will be done this week.

More about the `--local-modomics` parameter can be found by running `mimseq --help`

**Comment by wuxujia-dev** [comment]
您的邮件已收到，谢谢您的来信。

**Comment by drewjbeh** [comment]
Hi
Yes it has. Please install v1.3.8. Thanks
