### ISSUE TITLE
Issue after update

### ISSUE THREAD

**Issue by joegeorgeson** [nedialkova-lab/mim-tRNAseq#46]
Hi, I recently updated to v1.2.1 and receive the below error at the alignment step for the example data. This is with using the flag `--local-modomics`. Is there anything obvious for what might be wrong? Thanks!

```
(mimseq) [user@place mim-tRNAseq]$ mimseq --species Hsap --cluster-id 0.97 --threads 15 --min-cov 0.0005 --max-mismatches 0.075 --control-condition HEK293T -n hg38_test --out-dir hg38_HEK239vsK562 --max-multi 4 --remap --remap-mismatches 0.05 sampleData_HEKvsK562.txt --local-modomics
           _                 _   ____  _   _    _
 _ __ ___ (_)_ __ ___       | |_|  _ \| \ | |  / \   ___  ___  __ _
| '_ ` _ \| | '_ ` _ \ _____| __| |_) |  \| | / _ \ / __|/ _ \/ _` |
| | | | | | | | | | | |_____| |_|  _ <| |\  |/ ___ \\__ \  __/ (_| |
|_| |_| |_|_|_| |_| |_|      \__|_| \_\_| \_/_/   \_\___/\___|\__, |
                                                                 |_|

 Modification-induced misincorporation analysis of tRNA sequencing data

2023-10-08 14:42:33,258 [INFO ] mim-tRNAseq v1.2.1 run with command:
2023-10-08 14:42:33,258 [INFO ] ~/.conda/envs/mimseq/bin/mimseq --species Hsap --cluster-id 0.97 --threads 15 --min-cov 0.0005 --max-mismatches 0.075 --control-condition HEK293T -n hg38_test --out-dir hg38_HEK239vsK562 --max-multi 4 --remap --remap-mismatches 0.05 sampleData_HEKvsK562.txt --local-modomics
2023-10-08 14:42:33,259 [INFO ]
+----------------------------------------------+
| Starting analysis for hg38-tRNAs-filtered.fa |
+----------------------------------------------+
2023-10-08 14:42:33,259 [INFO ] Processing tRNA sequences...
2023-10-08 14:42:33,265 [INFO ] 34 introns registered...
2023-10-08 14:42:33,269 [INFO ] 22 mitochondrial tRNA sequences imported
2023-10-08 14:42:33,270 [INFO ] 600 cytosolic tRNA sequences imported
2023-10-08 14:42:33,270 [INFO ] Processing modomics database...
2023-10-08 14:42:33,270 [WARNI] Retrieval of Modomics database disabled. Using local files instead...
2023-10-08 14:42:33,270 [INFO ] Parsing local Modomics data...
2023-10-08 14:42:33,274 [INFO ] Number of Modomics entries for Homo sapiens: 45
2023-10-08 14:42:33,274 [INFO ] Number of Modomics entries for Escherichia coli: 43
2023-10-08 14:42:43,260 [INFO ]
+------------------------+
| Beginning SNP indexing |
+------------------------+
~/.conda/envs/mimseq/lib/python3.7/site-packages/Bio/SearchIO/_legacy/__init__.py:17: BiopythonDeprecationWarning: The 'Bio.SearchIO._legacy' module for parsing BLAST plain text output is deprecated and will be removed in a future release of Biopython. Consider generating your BLAST output for parsing as XML or tabular format instead.
  BiopythonDeprecationWarning,
2023-10-08 14:43:03,647 [INFO ] 622 total tRNA gene sequences (undetermined and nmt sequences excluded)
2023-10-08 14:43:03,648 [INFO ] 60 sequences with a match to Modomics dataset
2023-10-08 14:43:03,654 [INFO ] **** Clustering tRNA sequences ****
2023-10-08 14:43:03,655 [INFO ] Clustering tRNA sequences by 97% similarity...
2023-10-08 14:44:09,390 [INFO ] 321 clusters created from 622 tRNA sequences
2023-10-08 14:44:09,396 [INFO ] 220 modifications/cluster mismatches written to SNP index
2023-10-08 14:44:09,396 [INFO ] 49 A to G replacements in reference sequences for inosine modifications
2023-10-08 14:44:09,510 [INFO ]
+--------------------------+
| Generating GSNAP indices |
+--------------------------+
2023-10-08 14:44:30,328 [INFO ] Genome indices done...
2023-10-08 14:44:46,138 [INFO ] SNP indices done...
2023-10-08 14:44:46,139 [INFO ]
+-----------+
| Alignment |
+-----------+
2023-10-08 14:44:46,141 [INFO ] **** mimseq_hek_1.fastq.gz ****
2023-10-08 14:44:46,142 [INFO ] Aligning reads to Hsap_tRNAgenome...
Traceback (most recent call last):
  File "~/.conda/envs/mimseq/bin/mimseq", line 10, in <module>
    sys.exit(main())
  File "~/.conda/envs/mimseq/lib/python3.7/site-packages/mimseq/mimseq.py", line 411, in main
    args.misinc_thresh, args.mito, args.plastid, args.pretrnas, args.local_mod, args.p_adj, args.sampledata)
  File "~/.conda/envs/mimseq/lib/python3.7/site-packages/mimseq/mimseq.py", line 108, in mimseq
    snp_index_path, snp_index_name, out, threads, snp_tolerance, keep_temp, mismatches, map_round, remap)
  File "~/.conda/envs/mimseq/lib/python3.7/site-packages/mimseq/tRNAmap.py", line 48, in mainAlign
    unique_bam, librarySize, alignstats = mapReads(fq, genome_index_path, genome_index_name, snp_index_path, snp_index_name, threads, out_dir, snp_tolerance, keep_temp, mismatches, remap)
  File "~/.conda/envs/mimseq/lib/python3.7/site-packages/mimseq/tRNAmap.py", line 115, in mapReads
    subprocess.check_call(map_cmd, stderr = open(out_dir + "align.log", "a"))
  File "~/.conda/envs/mimseq/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gsnap', '--gunzip', '-D', 'hg38_HEK239vsK562/Hsap_tRNAgenome', '-d', 'Hsap_tRNAgenome', '-V', 'hg38_HEK239vsK562/Hsapsnp_index', '-v', 'hg38_test_modificationSNPs', '-t', '15', '--split-output', 'hg38_HEK239vsK562/mimseq_hek_1', '--format', 'sam', '--genome-unk-mismatch', '0', '--md-lowercase-snp', '--ignore-trim-in-filtering', '1', '--max-mismatches', '0.075', './mimseq_hek_1.fastq.gz']' returned non-zero exit status 255.

(mimseq) [user@place mim-tRNAseq]$ mimseq --version
           _                 _   ____  _   _    _
 _ __ ___ (_)_ __ ___       | |_|  _ \| \ | |  / \   ___  ___  __ _
| '_ ` _ \| | '_ ` _ \ _____| __| |_) |  \| | / _ \ / __|/ _ \/ _` |
| | | | | | | | | | | |_____| |_|  _ <| |\  |/ ___ \\__ \  __/ (_| |
|_| |_| |_|_|_| |_| |_|      \__|_| \_\_| \_/_/   \_\___/\___|\__, |
                                                                 |_|

 Modification-induced misincorporation analysis of tRNA sequencing data

mimseq v1.2.1
```

**Comment by nedialkova-lab** [comment]
Hi there - can you try with the most recent package version that is on Conda? That's 1.3.7. Let me know if the error persists. Were you able to run an older version on the sample data without any issues?

**Comment by nedialkova-lab** [comment]
Thanks - I am unable to reproduce the error so it may be an issue with some of the dependencies. Are you installing from Mambaforge as per our updated installation recommendations? Can you check which GSNAP version you've ended up with?

**Comment by joegeorgeson** [comment]
> Are you installing from Mambaforge as per our updated installation recommendations?

Yes, with command `mamba install -c bioconda mimseq`

> Can you check which GSNAP version you've ended up with?

Output below

```
(mimseq) [user@place ~]$ which gsnap
~/.conda/envs/mimseq/bin/gsnap
(mimseq) [user@place ~]$ ~/.conda/envs/mimseq/bin/gsnap --version
Note: ~/.conda/envs/mimseq/bin/gsnap.avx512 does not exist.  For faster speed, may want to compile package on an AVX512 machine
Note: ~/.conda/envs/mimseq/bin/gsnap.avx2 does not exist.  For faster speed, may want to compile package on an AVX2 machine
GSNAP version 2019-02-26 called with args: ~/.conda/envs/mimseq/bin/gsnap.sse42 --version

GSNAP: Genomic Short Nucleotide Alignment Program
Part of GMAP package, version 2019-02-26
Build target: x86_64-unknown-linux-gnu
Features: pthreads enabled, no alloca, zlib available, mmap available, littleendian, sigaction available, 64 bits available
Popcnt: mm_popcnt builtin_popcount
Builtin functions: builtin_clz builtin_ctz builtin_popcount
SIMD functions compiled: SSE2 SSSE3 SSE4.1 SSE4.2
Sizes: off_t (8), size_t (8), unsigned int (4), long int (8), long long int (8)
Default gmap directory (compiled): ~/.conda/envs/mimseq/share
Default gmap directory (environment): ~/.conda/envs/mimseq/share
Maximum stack read length: 300
Thomas D. Wu, Genentech, Inc.
Contact: twu@gene.com
```

**Comment by joegeorgeson** [comment]
I'm attaching the output of the `mamba install -c bioconda mimseq` command... please create a docker/sif for this once you have a stable version. 

[mimseq.mambaInstall.08Oct23.out.txt](https://github.com/nedialkova-lab/mim-tRNAseq/files/12840874/mimseq.mambaInstall.08Oct23.out.txt)

**Comment by nedialkova-lab** [comment]
We're continuously improving the package to expand the research questions it can help answer and most users have no issues with running it after installing from Conda - a docker is far from trivial to make and we have no plans (or funding) to do that at this point.

**Comment by drewjbeh** [comment]
Hi there, 

Thanks for getting in touch. Since the error is during alignment, could you have a look at the `align.log` output file to see what GSNAP is having a hard time with? You can past the output here (or attach it) so I can have a look as well.
Thanks.

**Comment by joegeorgeson** [comment]
Hi, so the `align.log` has nothing there. I've copied the contents of the output folder below. Let me know if something here might be useful.

```
(mimseq2) [user@place hg38_HEK239vsK562]$ lrt
total 723K
-rwxrwx--- 1 user grp  45K Oct  8 13:29 hg38_test_maturetRNA.bed
-rwxrwx--- 1 user grp  82K Oct  8 13:29 hg38_test_tRNATranscripts.fa
-rwxrwx--- 1 user grp  24K Oct  8 13:29 hg38_test_clusters.bed
-rwxrwx--- 1 user grp 3.1K Oct  8 13:29 hg38_testisoacceptorInfo.txt
-rwxrwx--- 1 user grp  42K Oct  8 13:29 hg38_testclusterInfo.txt
-rwxrwx--- 1 user grp 283K Oct  8 13:30 hg38_test_clusterTranscripts_align.stk
-rwxrwx--- 1 user grp  55K Oct  8 13:30 cm.log
-rwxrwx--- 1 user grp  43K Oct  8 13:30 hg38_test_clusterTranscripts.fa
-rwxrwx--- 1 user grp  16K Oct  8 13:30 hg38_test_modificationSNPs.txt
-rwxrwx--- 1 user grp  31K Oct  8 13:30 hg38_test_tRNA.gff
drwxrws--- 3 user grp 4.0K Oct  8 13:30 Hsap_tRNAgenome
-rwxrwx--- 1 user grp  20K Oct  8 13:30 genomeindex.log
drwxrws--- 2 user grp 4.0K Oct  8 13:30 Hsapsnp_index
-rwxrwx--- 1 user grp  41K Oct  8 13:30 snpindex.log
-rwxrwx--- 1 user grp    0 Oct  8 13:30 sampleData_HEKvsK562_cov.txt
-rwxrwx--- 1 user grp 2.4K Oct  8 13:30 mim-tRNAseq_23-27-09.log
-rwxrwx--- 1 user grp    0 Oct  8 13:30 align.log
```

**Comment by joegeorgeson** [comment]
> We're continuously improving the package to expand the research questions it can help answer and most users have no issues with running it after installing from Conda - a docker is far from trivial to make and we have no plans (or funding) to do that at this point.

It seems there were recent chages to mambaforge that might affect the portability. It didn't work for me, but I created a .sif file and could run there. I'm copying a Singularity file below that can be created with `singularity build --fakeroot mimseq.sif Singularity &> build.out` and have also copied the log...

**Comment by drewjbeh** [comment]
Yeah this indicates to me that some versions of the GMAP/GSNAP index and SNP index building tools had their versions changed while GSNAP itself stayed the correct version. We had a similar issue with a colleague using a version that I soon after updated with a fix. Perhaps you got this version unluckily. 
Could you check the `snpindex.log` contents - since `align.log` is empty this indicates that alignment doesn't even start but indexing seems to finish. 
More importantly, could you check the versions of `gmap_build` and `snpindex` commands. These should match that of `gsnap`. If they don't match then they need to be reinstalled. Honestly, removing the environment and creating a new one is probably safest and easiest (and quickest) at this point regarding dependencies. 

Nice work with the singularity file, if that's working for you then go ahead and use that. I assume it works because it's acting the same as a "fresh" Fonda environment. Would be curious to know if a new cobra environment also fixes things...

**Comment by joegeorgeson** [comment]
The `snpindex.log` is identical between my local build and the container. My local is with centos and the container with ubuntu - maybe something related to that ¯\\_(ツ)_/¯ ? 

`gmap_build`, `gsnap` and `snpindex` are all the same version '2019-02-26' in both builds

Anyhoo, it seems mamba is 'Discouraged as of September 2023' https://github.com/conda-forge/miniforge#miniforge-pypy3

Feel free to close this thread. Thanks
