### ISSUE TITLE
Error in the Alignment step

### ISSUE THREAD

**Issue by marctormo** [nedialkova-lab/mim-tRNAseq#47]
Hi there,

I'm trying to run mimseq (with --local_modomics) and I'm obtaining an error in the alignment step:

```
$ rm -fr $output;mimseq --local-modomics --species $species --cluster-id 0.97 --threads 4 --min-cov 0.0005 --max-mismatches 0.1 --control-condition $control -n $prefix --out-dir $output --max-multi 4 --remap --remap-mismatches 0.075 $data
...
(I'm ignoring the full output as it's correct)
...
+-----------+ 			
| Alignment |			
+-----------+
2023-10-20 13:49:47,903 [INFO ] **** mimseq_hek_1.fastq.gz ****
2023-10-20 13:49:47,904 [INFO ] Aligning reads to Hsap_tRNAgenome...
Traceback (most recent call last):
  File "/gpfs42/robbyfs/scratch/lab_jdiez/mpuig/conda/mimseq_env/bin/mimseq", line 10, in <module>
    sys.exit(main())
  File "/scratch/lab_jdiez/mpuig/conda/mimseq_env/lib/python3.7/site-packages/mimseq/mimseq.py", line 424, in main
    args.misinc_thresh, args.mito, args.plastid, args.pretrnas, args.local_mod, args.p_adj, args.crosstalks, args.sampledata)
  File "/scratch/lab_jdiez/mpuig/conda/mimseq_env/lib/python3.7/site-packages/mimseq/mimseq.py", line 109, in mimseq
    snp_index_path, snp_index_name, out, threads, snp_tolerance, keep_temp, mismatches, map_round, remap)
  File "/scratch/lab_jdiez/mpuig/conda/mimseq_env/lib/python3.7/site-packages/mimseq/tRNAmap.py", line 48, in mainAlign
    unique_bam, librarySize, alignstats = mapReads(fq, genome_index_path, genome_index_name, snp_index_path, snp_index_name, threads, out_dir, snp_tolerance, keep_temp, mismatches, remap)
  File "/scratch/lab_jdiez/mpuig/conda/mimseq_env/lib/python3.7/site-packages/mimseq/tRNAmap.py", line 115, in mapReads
    subprocess.check_call(map_cmd, stderr = open(out_dir + "align.log", "a"))
  File "/scratch/lab_jdiez/mpuig/conda/mimseq_env/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gsnap', '--gunzip', '-D', '/scratch/lab_jdiez/mpuig/tRNA-seq/example_data/mimseq_Output/Hsap_tRNAgenome', '-d', 'Hsap_tRNAgenome', '-V', '/scratch/lab_jdiez/mpuig/tRNA-seq/example_data/mimseq_Output/Hsapsnp_index', '-v', 'test_modificationSNPs', '-t', '4', '--split-output', '/scratch/lab_jdiez/mpuig/tRNA-seq/example_data/mimseq_Output/mimseq_hek_1', '--format', 'sam', '--genome-unk-mismatch', '0', '--md-lowercase-snp', '--ignore-trim-in-filtering', '1', '--max-mismatches', '0.1', './mimseq_hek_1.fastq.gz']' returned non-zero exit status 9.
```

Do you know if this is a installation problem or something related with our data?

Many thanks!
Marc

**Comment by drewjbeh** [comment]
Hi there,

Could you please take a look at the file `align.log` for further hints. Paste the output here if there's nothing obvious. Thanks!

**Comment by marctormo** [comment]
It was obvious XD
I misplaced the path to fastq files. Now it's working.

Thanks and sorry for the inconvenience.
Marc
