### ISSUE TITLE
Installation error: Bio.Alphabet has been removed from Biopython

### ISSUE THREAD

**Issue by mt1022** [nedialkova-lab/mim-tRNAseq#5]
Hi, I installed `mimsq` following the README. But I couldn't run it after installation due to the following error:

```
$ mimseq --help
Traceback (most recent call last):
  File "/lustre/user/xxx/anaconda3/envs/mimseq/bin/mimseq", line 6, in <module>
    from mimseq.mimseq import main
  File "/lustre/user/xxx/anaconda3/envs/mimseq/lib/python3.7/site-packages/mimseq/mimseq.py", line 17, in <module>
    from .tRNAtools import modsToSNPIndex, generateGSNAPIndices, newModsParser, tidyFiles
  File "/lustre/userxxx/anaconda3/envs/mimseq/lib/python3.7/site-packages/mimseq/tRNAtools.py", line 11, in <module>
    from Bio import Alphabet
  File "/lustre/user/xxx/anaconda3/envs/mimseq/lib/python3.7/site-packages/Bio/Alphabet/__init__.py", line 21, in <module>
    "Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information."
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.
```
A workaround is to downgrade `biopyhon` to vesion 1.77. However, I think an update of `mimseq` would be better.

**Comment by drewjbeh** [comment]
Hi there,

Thanks for the heads-up. I already noticed this problem before and have adjusted `mimseq` code accordingly. The fix will be implemented in the next release.
