### ISSUE TITLE
Incomplete refactor in tRNAtools

### ISSUE THREAD

**Issue by kelly-sovacool** [nedialkova-lab/mim-tRNAseq#59]
Looks like there are some leftover functions that didn't quite get refactored with the new code for parsing the mod table. The master branch is failing on the test dataset:

```sh
mimseq --species Hsap --cluster-id 0.97 --threads 2 --min-cov 0.0005 --max-mismatches 0.075 --control-condition HEK293T -n hg38_test --out-dir hg38_HEK239vsK562 --max-multi 4 --remap --remap-mismatches 0.05 sampleData_HEKvsK562.txt
```
```
           _                 _   ____  _   _    _                   
 _ __ ___ (_)_ __ ___       | |_|  _ \| \ | |  / \   ___  ___  __ _ 
| '_ ` _ \| | '_ ` _ \ _____| __| |_) |  \| | / _ \ / __|/ _ \/ _` |
| | | | | | | | | | | |_____| |_|  _ <| |\  |/ ___ \\__ \  __/ (_| |
|_| |_| |_|_|_| |_| |_|      \__|_| \_\_| \_/_/   \_\___/\___|\__, |
                                                                 |_|

 Modification-induced misincorporation analysis of tRNA sequencing data

2023-11-06 12:41:35,511 [INFO ] mim-tRNAseq v1.3.7 run with command:
2023-11-06 12:41:35,511 [INFO ] /opt/homebrew/bin/mimseq --species Hsap --cluster-id 0.97 --threads 2 --min-cov 0.0005 --max-mismatches 0.075 --control-condition HEK293T -n hg38_test --out-dir hg38_HEK239vsK562 --max-multi 4 --remap --remap-mismatches 0.05 sampleData_HEKvsK562.txt
2023-11-06 12:41:35,857 [ERROR] Error in connecting to Modomics: HTTPSConnectionPool(host='www.genesilico.pl', port=443): Max retries exceeded with url: /modomics/api/modifications (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1002)'))). Using local Modomics files...
2023-11-06 12:41:35,859 [INFO ] Parsing local Modification data...
Traceback (most recent call last):
  File "/opt/homebrew/bin/mimseq", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mimseq/mimseq.py", line 418, in main
    mimseq(args.trnas, args.trnaout, args.name, args.species, args.out, args.cluster, args.cluster_id, args.cov_diff, \
  File "/opt/homebrew/lib/python3.11/site-packages/mimseq/mimseq.py", line 99, in mimseq
    = modsToSNPIndex(gtRNAdb = trnas, tRNAscan_out = trnaout, mitotRNAs = mito_trnas, plastidtRNAs = plastid_trnas, experiment_name = name, out_dir = out, double_cca = double_cca, threads = threads, snp_tolerance = snp_tolerance, cluster = cluster, cluster_id = cluster_id, posttrans_mod_off = posttrans, pretrnas = pretrnas, local_mod = local_mod)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mimseq/tRNAtools.py", line 378, in modsToSNPIndex
    tRNA_dict, modomics_dict, species = tRNAparser(gtRNAdb, tRNAscan_out, mitotRNAs, plastidtRNAs, posttrans_mod_off, double_cca, pretrnas, local_mod)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mimseq/tRNAtools.py", line 36, in tRNAparser
    modifications = modificationParser(modifications_file, fetch)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mimseq/tRNAtools.py", line 282, in modificationParser
    mods = open(modifications_table, 'r', encoding='utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not TextIOWrapper
```

**Comment by drewjbeh** [comment]
Thanks for finding that. Should be fixed now
