### ISSUE TITLE
mimseq error: Faceting variables must have at least one value

### ISSUE THREAD

**Issue by mt1022** [nedialkova-lab/mim-tRNAseq#6]
Hi,

I was running `mimseq` with fly tRNA-seq data:
```
mimseq --species Dmel --cluster --cluster-id 0.95 --snp-tolerance --cca-analysis \
    --threads 16 --min-cov 2000 --max-mismatches 0.1 --control-condition S1 \
    -n test --out-dir test --max-multi 4 --remap --remap-mismatches 0.075 test.txt
```
The program aborted due to the `Error: Faceting variables must have at least one value`. I noticed that two count tables had been generated:

```
...
2021-04-19 16:45:04,717 [INFO ] ** Read counts per anticodon saved to test/counts/Anticodon_counts.txt **
2021-04-19 16:45:04,718 [INFO ] ** Read counts per isodecoder saved to test/counts/Isodecoder_counts.txt **
...
```
I am not sure whether this is the final results of anticodon counts. If I am only interested in tRNA expression levels, could I ignore the error and go on with the count tables?

Thanks very much for any advice!

The complete mimseq log and error message:
```
           _                 _   ____  _   _    _
 _ __ ___ (_)_ __ ___       | |_|  _ \| \ | |  / \   ___  ___  __ _
| '_ ` _ \| | '_ ` _ \ _____| __| |_) |  \| | / _ \ / __|/ _ \/ _` |
| | | | | | | | | | | |_____| |_|  _ <| |\  |/ ___ \\__ \  __/ (_| |
|_| |_| |_|_|_| |_| |_|      \__|_| \_\_| \_/_/   \_\___/\___|\__, |
                                                                 |_|

 Modification-induced misincorporation analysis of tRNA sequencing data

2021-04-19 16:25:15,720 [INFO ] mim-tRNAseq v0.2.5.3 run with command:
2021-04-19 16:25:15,721 [INFO ] /lustre/user/xxx/anaconda3/envs/mimseq/bin/mimseq --species Dmel --cluster --cluster-id 0.95 --snp-tolerance --cca-analysis --threads 16 --min-cov 2000 --max-mismatches 0.1 --control-condition S1 -n test --out-dir test --max-multi 4 --remap --remap-mismatches 0.075 test.txt
2021-04-19 16:25:15,725 [INFO ]
+--------------------------------------------+
| Starting analysis for dm6_eColitK-tRNAs.fa |
+--------------------------------------------+
2021-04-19 16:25:15,725 [INFO ] Processing tRNA sequences...
2021-04-19 16:25:15,733 [INFO ] 15 introns registered...
2021-04-19 16:25:15,740 [INFO ] 294 cytosolic and 22 mitochondrial tRNA sequences imported
2021-04-19 16:25:15,740 [INFO ] Processing modomics database...
2021-04-19 16:25:19,134 [INFO ] Number of Modomics entries for Escherichia coli: 43
2021-04-19 16:25:19,134 [INFO ] Number of Modomics entries for Drosophila melanogaster: 14
2021-04-19 16:25:24,104 [INFO ]
+------------------------+
| Beginning SNP indexing |
+------------------------+
2021-04-19 16:27:54,219 [INFO ] 316 total tRNA gene sequences (undetermined and nmt sequences excluded)
2021-04-19 16:27:54,220 [INFO ] 72 sequences with a match to Modomics dataset
2021-04-19 16:27:54,227 [INFO ] **** Clustering tRNA sequences ****
2021-04-19 16:27:54,228 [INFO ] Clustering tRNA sequences by 95% similarity...
2021-04-19 16:27:59,776 [INFO ] 80 clusters created from 316 tRNA sequences
2021-04-19 16:27:59,779 [INFO ] 78 modifications written to SNP index
2021-04-19 16:27:59,780 [INFO ] 2 A to G replacements in reference sequences for inosine modifications
2021-04-19 16:27:59,978 [INFO ]
+--------------------------+
| Generating GSNAP indices |
+--------------------------+
2021-04-19 16:28:24,667 [INFO ] Genome indices done...
2021-04-19 16:28:54,485 [INFO ] SNP indices done...
2021-04-19 16:28:54,486 [INFO ]
+-----------+
| Alignment |
+-----------+
2021-04-19 16:28:54,489 [INFO ] **** S1.fq ****
2021-04-19 16:28:54,490 [INFO ] Aligning reads to Dmel_tRNAgenome...
2021-04-19 16:29:35,950 [INFO ] Compressing SAM files, sorting, and computing mapping stats...
[bam_sort_core] merging from 0 files and 16 in-memory blocks...
2021-04-19 16:29:42,609 [INFO ] **** S2.fq ****
2021-04-19 16:29:42,609 [INFO ] Aligning reads to Dmel_tRNAgenome...
2021-04-19 16:30:53,118 [INFO ] Compressing SAM files, sorting, and computing mapping stats...
[bam_sort_core] merging from 0 files and 16 in-memory blocks...
2021-04-19 16:31:05,270 [INFO ] Alignment statistics and plot saved to test/align/mapping_stats.txt
2021-04-19 16:31:05,272 [INFO ]
+------------------------------------------------------------------------------+
| Characterizing cluster mismatches for read splitting by unique tRNA sequence |
+------------------------------------------------------------------------------+
2021-04-19 16:31:05,272 [INFO ] ** Assessing mismatches between cluster members and parent... **
2021-04-19 16:31:07,243 [INFO ] Total unique tRNA sequenes in input: 111
2021-04-19 16:31:07,244 [INFO ] Total deconvoluted unique tRNA sequences: 105
2021-04-19 16:31:07,245 [INFO ]
+--------------------------------------------------------------------+
| Analysing misincorporations and stops to RT, and analysing 3' ends |
+--------------------------------------------------------------------+
2021-04-19 16:31:07,248 [INFO ] ** Discovering unannotated modifications for realignment **
[E::idx_find_and_load] Could not retrieve index file for 'test/S1.fq.unpaired_uniq.bam'
[E::idx_find_and_load] Could not retrieve index file for 'test/S2.fq.unpaired_uniq.bam'
2021-04-19 16:31:07,347 [INFO ] Analysing test/S1.fq.unpaired_uniq.bam...
2021-04-19 16:31:07,348 [INFO ] Analysing test/S2.fq.unpaired_uniq.bam...
2021-04-19 16:34:11,469 [INFO ] Finding potential unannotated mods for test/S1.fq.unpaired_uniq.bam
2021-04-19 16:34:11,748 [INFO ] Analysis complete for test/S1.fq.unpaired_uniq.bam...
2021-04-19 16:36:16,839 [INFO ] Finding potential unannotated mods for test/S2.fq.unpaired_uniq.bam
2021-04-19 16:36:17,113 [INFO ] Analysis complete for test/S2.fq.unpaired_uniq.bam...
2021-04-19 16:36:17,188 [INFO ]
+------------------+
| Parsing new mods |
+------------------+
2021-04-19 16:36:17,189 [INFO ] 6 new predicted position 34 inosines
2021-04-19 16:36:17,189 [INFO ] 5 new predicted modifications
2021-04-19 16:36:17,200 [INFO ] 89 modifications written to SNP index
2021-04-19 16:36:17,200 [INFO ]
+----------------------------+
| Regenerating GSNAP indices |
+----------------------------+
2021-04-19 16:36:17,201 [WARNI] Genome index folder found! Rebuilding index anyway...
2021-04-19 16:36:41,858 [INFO ] Genome indices done...
2021-04-19 16:36:41,859 [WARNI] SNP index folder found! Rebuilding index anyway...
2021-04-19 16:37:11,633 [INFO ] SNP indices done...
2021-04-19 16:37:11,635 [INFO ]
+------------------+
| Realigning reads |
+------------------+
2021-04-19 16:37:11,639 [INFO ] **** S1.fq ****
2021-04-19 16:37:11,640 [INFO ] Aligning reads to Dmel_tRNAgenome...
2021-04-19 16:37:53,182 [INFO ] Compressing SAM files, sorting, and computing mapping stats...
[bam_sort_core] merging from 0 files and 16 in-memory blocks...
2021-04-19 16:38:00,202 [INFO ] **** S2.fq ****
2021-04-19 16:38:00,204 [INFO ] Aligning reads to Dmel_tRNAgenome...
2021-04-19 16:39:10,079 [INFO ] Compressing SAM files, sorting, and computing mapping stats...
[bam_sort_core] merging from 0 files and 16 in-memory blocks...
2021-04-19 16:39:21,215 [INFO ] Alignment statistics and plot saved to test/align/mapping_stats.txt
2021-04-19 16:39:21,216 [INFO ]
+--------------------------------------------------------------------+
| Analysing misincorporations and stops to RT, and analysing 3' ends |
+--------------------------------------------------------------------+
2021-04-19 16:39:21,217 [WARNI] Rewriting over old mods and CCA files...
[E::idx_find_and_load] Could not retrieve index file for 'test/S2.fq.unpaired_uniq.bam'
[E::idx_find_and_load] Could not retrieve index file for 'test/S1.fq.unpaired_uniq.bam'
2021-04-19 16:39:21,306 [INFO ] Analysing test/S2.fq.unpaired_uniq.bam...
2021-04-19 16:39:21,306 [INFO ] Analysing test/S1.fq.unpaired_uniq.bam...
2021-04-19 16:42:19,754 [INFO ] Finding potential unannotated mods for test/S1.fq.unpaired_uniq.bam
2021-04-19 16:42:20,120 [INFO ] Building modification, stop and count data tables for test/S1.fq.unpaired_uniq.bam
2021-04-19 16:42:56,006 [INFO ] Analysis complete for test/S1.fq.unpaired_uniq.bam...
2021-04-19 16:44:19,644 [INFO ] Finding potential unannotated mods for test/S2.fq.unpaired_uniq.bam
2021-04-19 16:44:20,014 [INFO ] Building modification, stop and count data tables for test/S2.fq.unpaired_uniq.bam
2021-04-19 16:44:58,319 [INFO ] Analysis complete for test/S2.fq.unpaired_uniq.bam...
2021-04-19 16:44:58,447 [INFO ]
+------------------+
| Parsing new mods |
+------------------+
2021-04-19 16:44:58,448 [INFO ] 0 new predicted position 34 inosines
2021-04-19 16:44:58,448 [INFO ] 0 new predicted modifications
2021-04-19 16:44:58,457 [INFO ] 83 modifications written to SNP index
2021-04-19 16:45:03,085 [INFO ] 17 clusters filtered out according to minimum coverage threshold: 2000
2021-04-19 16:45:04,717 [INFO ] ** Read counts per anticodon saved to test/counts/Anticodon_counts.txt **
2021-04-19 16:45:04,718 [INFO ] ** Read counts per isodecoder saved to test/counts/Isodecoder_counts.txt **
2021-04-19 16:45:04,753 [INFO ] Plotting modification and RT stop data...
Error: Faceting variables must have at least one value
Backtrace:
     x
  1. \-ggplot2::ggsave(...)
  2.   +-grid::grid.draw(plot)
  3.   \-ggplot2:::grid.draw.ggplot(plot)
  4.     +-base::print(x)
  5.     \-ggplot2:::print.ggplot(x)
  6.       +-ggplot2::ggplot_build(x)
  7.       \-ggplot2:::ggplot_build.ggplot(x)
  8.         \-layout$setup(data, plot$data, plot$plot_env)
  9.           \-ggplot2:::f(..., self = self)
 10.             \-self$facet$compute_layout(data, self$facet_params)
 11.               \-ggplot2:::f(...)
 12.                 \-ggplot2::combine_vars(data, params$plot_env, rows, drop = params$drop)
Warning message:
In brewer.pal(color_num, "Greys") :
  minimal value for n is 3, returning requested palette with 3 different levels

Execution halted
Traceback (most recent call last):
  File "/lustre/user/xxx/anaconda3/envs/mimseq/bin/mimseq", line 10, in <module>
    sys.exit(main())
  File "/lustre/user/xxx/anaconda3/envs/mimseq/lib/python3.7/site-packages/mimseq/mimseq.py", line 303, in main
    args.misinc_thresh, args.mito, args.pretrnas, args.sampledata)
  File "/lustre/user/xxx/anaconda3/envs/mimseq/lib/python3.7/site-packages/mimseq/mimseq.py", line 129, in mimseq
    subprocess.check_call(modplot_cmd)
  File "/lustre/user/xxx/anaconda3/envs/mimseq/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['Rscript', '/lustre/user/xxx/anaconda3/envs/mimseq/lib/python3.7/site-packages/mimseq/modPlot.R', 'test/', '9_20_26_32_34_37_58', '0_1_2_3_4_5_6_7_-_-_8_-_9_-_10_11_12_13_14_15_16_17_17a_18_19_20_20a_20b_21_22_23_24_25_26_27_28_29_30_31_32_33_34_35_36_37_38_39_40_41_42_43_44_45_e_e_e_e_e_e_e_e_e_e_e_e_e_e_e_e_e_e_e_46_47_48_49_50_51_52_53_54_55_56_57_58_59_-_-_60_-_61_-_-_62_63_64_-_65_66_67_68_-_69_70_71_72_73_74_75_76', '0.1', '/lustre/user/xxx/anaconda3/envs/mimseq/lib/python3.7/site-packages/mimseq/data/dm6-eColitK/dm6-mitotRNAs.fa']' returned non-zero exit status 1.
```

**Comment by drewjbeh** [comment]
Hi there,

Thanks for bringing up this error, I hope I can help (and sorry for the delayed response).

Firstly, I would recommend upgrading to the newest version of mimseq by running `conda update mimseq`.

The `Error: Faceting variables must have at least one value` error is from ggplot2 when it tries to make the plots from the modification data. It indicates to me that there is little to no data in the `/mods` folder data tables. Could you confirm this by looking at, for example, the `mismatchTable.csv` file and confirming there is data here? This should be a very large table, but even if there is data in here it might be very sparse and this would still cause issues. 

This can arise due to low alignment rates, or very fragmented RNA with low misincoporations, which in turn can arise from poor sequencing data or an inefficient RT during library prep (did you use our protocol for library prep with TGIRT?). I suggest you look at `mapping_stats.txt` and ensure that the proportion of uniquely mapped reads is high (at least 60% or so, but we were able to get above 80% with fly data). If this is very low I would consider making the libraries again and trying to optimise it so you get good RT, PCR and lots of tRNA sequenced reads that align uniquely to the reference.

In terms of using the data in counts; you can definitely use these counts as expression values but **PLEASE NOTE** that these counts are raw count values not normalised in any way. Typically we use the counts produced by DESeq2 (`counts(dds, normalized = TRUE)`), which can be found in the `DESeq2` folder in any of the `diffexpr-results.csv` files appended as a column of normalised counts for every sample. Of course, your error occurs before DESeq2 is run and so you will not have these files unfortunately. You can import the `counts/Isodecoder_counts.txt` into your own DESeq2 analysis and follow the standard protocol to generate normalised counts but this will be much easier if mimseq could do this for you! So best case would be if we can fix your error.

Hopefully by upgrading you might get some new important updates and fixes that can allow betting mapping and will solve this problem, let me know how it goes.

**Comment by mt1022** [comment]
Thanks for the troubleshooting. I was analyzed a tRNA-seq data generated with a custom protocol that is very similar to hydro-tRNAseq. From the `mapping_stats.txt` file, about 70% reads are uniquely mapped. `mods/mismatchTable.csv` file is not empty and quite large (9.7M) However, the values in the proportion column are very small (1e-5 ~ 1e-3).

I upgraded `mimseq` to the lastest version (v0.3.3.2 I believe) and tested with the example dataset. I still could not get `mimseq` to run correctly. The error message is:

```
mimseq --species Hsap --cluster --cluster-id 0.95 --threads 15 --min-cov 2000 --max-mismatches 0.1 --control-condition HEK293T -n hg19_test --out-dir hg19_HEK239vsK562 --max-multi 4 --remap --remap-mismatches 0.075 sampleData_HEKvsK562.txt
           _                 _   ____  _   _    _
 _ __ ___ (_)_ __ ___       | |_|  _ \| \ | |  / \   ___  ___  __ _
| '_ ` _ \| | '_ ` _ \ _____| __| |_) |  \| | / _ \ / __|/ _ \/ _` |
| | | | | | | | | | | |_____| |_|  _ <| |\  |/ ___ \\__ \  __/ (_| |
|_| |_| |_|_|_| |_| |_|      \__|_| \_\_| \_/_/   \_\___/\___|\__, |
                                                                 |_|

 Modification-induced misincorporation analysis of tRNA sequencing data

2021-04-26 13:31:14,217 [INFO ] mim-tRNAseq v0.3.3.2 run with command:
2021-04-26 13:31:14,217 [INFO ] /lustre/user/xxx/anaconda3/envs/mimseq/bin/mimseq --species Hsap --cluster --cluster-id 0.95 --threads 15 --min-cov 2000 --max-mismatches 0.1 --control-condition HEK293T -n hg19_test --out-dir hg19_HEK239vsK562 --max-multi 4 --remap --remap-mismatches 0.075 sampleData_HEKvsK562.txt
2021-04-26 13:31:14,221 [INFO ]
+---------------------------------------+
| Starting analysis for hg19_eColitK.fa |
+---------------------------------------+


+------------------+
| Parsing new mods |
+------------------+
2021-04-26 13:58:19,848 [INFO ] 0 new predicted position 34 inosines
2021-04-26 13:58:19,850 [INFO ] 4 new predicted modifications
2021-04-26 13:58:19,897 [INFO ] 277 clusters filtered out according to minimum coverage threshold: 2000.0 total read coverage per isodecoder.
2021-04-26 13:58:47,940 [INFO ] Output final tables, counts and new mods...
2021-04-26 13:58:54,010 [INFO ] ** Read counts per anticodon saved to hg19_HEK239vsK562/counts/Anticodon_counts.txt **
2021-04-26 13:58:54,010 [INFO ] ** Read counts per isodecoder saved to hg19_HEK239vsK562/counts/Isodecoder_counts.txt **
2021-04-26 13:58:54,145 [INFO ] Plotting modification and RT stop data...
Error in lastlevel(unique(mods_agg$condition), control_cond) :
  input for contrast combinations not a factor
Calls: levels -> lastlevel
Execution halted
2021-04-26 14:00:01,370 [INFO ]
+-----------------+
| 3'-CCA analysis |
+-----------------+
Error in axes$y$left[[1]]$children$axis$grobs[[lab_idx]] :
  attempt to select less than one element in get1index
Calls: ggsave ... ggplot_gtable.ggplot_built -> <Anonymous> -> f -> <Anonymous> -> f
Execution halted
Traceback (most recent call last):
  File "/lustre/user/xxx/anaconda3/envs/mimseq/bin/mimseq", line 8, in <module>
    sys.exit(main())
  File "/lustre/user/xxx/anaconda3/envs/mimseq/lib/python3.7/site-packages/mimseq/mimseq.py", line 361, in main
    args.misinc_thresh, args.mito, args.pretrnas, args.local_mod, args.sampledata)
  File "/lustre/user/xxx/anaconda3/envs/mimseq/lib/python3.7/site-packages/mimseq/mimseq.py", line 166, in mimseq
    plotCCA(out, double_cca)
  File "/lustre/user/xxx/anaconda3/envs/mimseq/lib/python3.7/site-packages/mimseq/mmQuant.py", line 781, in plotCCA
    subprocess.check_call(command)
  File "/lustre/user/xxx/anaconda3/envs/mimseq/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['Rscript', '/lustre/user/xxx/anaconda3/envs/mimseq/lib/python3.7/site-packages/mimseq/ccaPlots.R', 'hg19_HEK239vsK562/CCAanalysis/AlignedDinucProportions.csv', 'hg19_HEK239vsK562/CCAanalysis//CCAcounts.csv', 'hg19_HEK239vsK562/CCAanalysis/', 'False', '/lustre/user/xxx/anaconda3/envs/mimseq/lib/python3.7/site-packages/mimseq/facet_share.R']' returned non-zero exit status 1.
```

**Comment by drewjbeh** [comment]
Ok this one is because you might have upgraded your `ggplot2` package in R, or perhaps the environment you're working in has a newer version than required (v 3.2.1). 
You can downgrade ggplot2 in your mimseq environment. Or what I suggest (as I have recently helped some colleagues with errors last week) is to reinstall `mim-tRNAseq` in a fresh environment. This seemed to fix all issues:
1. Remove old environment: `conda env remove -n mimseq`
2. Make new env: `conda create -n mimseq python=3.7`
3. `conda activate mimseq`
4. Install mamba: `conda install mamba`
5. Use mamba to install latest mimseq: `mamba install -c bioconda mimseq`

**Comment by mt1022** [comment]
Thanks for the instructions. It worked for the example dataset! But there seems to be something wrong with my test data. The program fails at the plotting step when parsing new mods. But it finished all the other analyses. I am not sure whether the plotting error is related to the lacking of replicates (i.e, are you using replicates as one faceting variable for plotting?).

```
+------------------+ 		
| Parsing new mods |		
+------------------+
2021-04-27 10:42:08,333 [INFO ] 0 new predicted position 34 inosines
2021-04-27 10:42:08,333 [INFO ] 0 new predicted modifications
2021-04-27 10:42:08,363 [INFO ] 16 clusters filtered out according to minimum coverage threshold: 2000.0 total read coverage per isodecoder.
2021-04-27 10:42:29,488 [INFO ] Output final tables, counts and new mods...
2021-04-27 10:42:30,340 [INFO ] ** Read counts per anticodon saved to mimseq_dmel/counts/Anticodon_counts.txt **
2021-04-27 10:42:30,340 [INFO ] ** Read counts per isodecoder saved to mimseq_dmel/counts/Isodecoder_counts.txt **
2021-04-27 10:42:30,375 [INFO ] Plotting modification and RT stop data...
Error: Faceting variables must have at least one value
In addition: Warning messages:
1: In brewer.pal(color_num, "Greys") :
  minimal value for n is 3, returning requested palette with 3 different levels

2: In brewer.pal(color_num, "Greys") :
  minimal value for n is 3, returning requested palette with 3 different levels

Execution halted
2021-04-27 10:43:14,917 [INFO ] 
+-----------------+		
| 3'-CCA analysis |		
+-----------------+
2021-04-27 10:43:19,301 [INFO ] CCA analysis done and plots created. Located in mimseq_dmel/CCAanalysis/
2021-04-27 10:43:19,302 [INFO ] 
+-----------------------------------+		
| Calculating coverage and plotting |		
+-----------------------------------+
2021-04-27 10:43:54,810 [INFO ] 
+----------------------------------------------+	
| Differential expression analysis with DESeq2 |	
+----------------------------------------------+
converting counts to integer mode
2021-04-27 10:44:35,815 [INFO ] [1] "DESeq2 analysis not run as there are no sample replicates!"
2021-04-27 10:44:36,110 [INFO ] DESeq2 outputs located in: mimseq_dmel/DESeq2
```

**Comment by drewjbeh** [comment]
The lack of replicates shouldn't impact the plotting as far as I know but the error could be coming from another error that I've overlooked. It might be since you generated your libraries similarly to hydro-tRNAseq that there are very few misincorporations at modifications and this could let to problems when plotting mods. 
It would be great if you would be willing to share some files with me to troubleshoot this. The tables in the `/mods` folder would be enough, specifically `mismatchTable.csv`, `RTstopTable.csv`, `readthroughTable.csv` and `modContext.txt`

**Comment by mt1022** [comment]
The four tables are attached as follows. Thanks for looking into this issue.

[mods_tables.zip](https://github.com/nedialkova-lab/mim-tRNAseq/files/6391442/mods_tables.zip)

**Comment by drewjbeh** [comment]
Great, thanks!
I did some testing and fixed a bug. It is related to the very little misincorporation data in your libraries, likely due to the hydro-seq workflow instead of using TGIRT for example as in the mim-tRNAseq method. Specifically, in your case, there is not enough data for mito modifications to make one of the plots. With the fix, this plot is simply skipped.

For now I haven't released the fix as a new version as I am also working on some other updates. But I attach a new `modPlot.R` file that I hope works for you. 
Please could you copy (and replace the old version) of this script into where `mimseq` is installed (seems to be `/lustre/user/xxx/anaconda3/envs/mimseq/lib/python3.7/site-packages/mimseq/` from your error logs above, although the user might have been edited by you?) and then rerun `mimseq` as you did before. Fingers crossed it works!
[modPlot.R.zip](https://github.com/nedialkova-lab/mim-tRNAseq/files/6397812/modPlot.R.zip)

**Comment by mt1022** [comment]
Hi Drew, 

The patch works fine for my test data. Thanks very much for spending the time and efforts investigating this issue and fixing it :)

Cheers!
