### ISSUE TITLE
cmalign dependency when installing from source

### ISSUE THREAD

**Issue by kelly-sovacool** [nedialkova-lab/mim-tRNAseq#61]
mimseq installed from source fails due to missing `cmalign` command. Likely this dependency needs to be mentioned in the README for users installing with pip? 

```sh
mimseq --species Hsap --cluster-id 0.97 --threads 2 --min-cov 0.0005 --max-mismatches 0.075 --control-condition HEK293T -n hg38_test --out-dir hg38_HEK239vsK562 --max-multi 4 --remap --remap-mismatches 0.05 --local-modomics sampleData_HEKvsK562.txt
```

```
           _                 _   ____  _   _    _                   
 _ __ ___ (_)_ __ ___       | |_|  _ \| \ | |  / \   ___  ___  __ _ 
| '_ ` _ \| | '_ ` _ \ _____| __| |_) |  \| | / _ \ / __|/ _ \/ _` |
| | | | | | | | | | | |_____| |_|  _ <| |\  |/ ___ \\__ \  __/ (_| |
|_| |_| |_|_|_| |_| |_|      \__|_| \_\_| \_/_/   \_\___/\___|\__, |
                                                                 |_|

 Modification-induced misincorporation analysis of tRNA sequencing data

2023-11-07 09:13:12,870 [INFO ] mim-tRNAseq v1.3.7 run with command:
2023-11-07 09:13:12,870 [INFO ] /opt/homebrew/bin/mimseq --species Hsap --cluster-id 0.97 --threads 2 --min-cov 0.0005 --max-mismatches 0.075 --control-condition HEK293T -n hg38_test --out-dir hg38_HEK239vsK562 --max-multi 4 --remap --remap-mismatches 0.05 --local-modomics sampleData_HEKvsK562.txt
2023-11-07 09:13:12,870 [WARNI] Retrieval of Modomics database disabled. Using local files instead...
2023-11-07 09:13:12,871 [INFO ] Parsing local Modification data...
2023-11-07 09:13:12,872 [INFO ] 
+-----------------------------------------+
| Starting analysis for hg38-tRNAs-all.fa |
+-----------------------------------------+
2023-11-07 09:13:12,872 [INFO ] Processing tRNA sequences...
2023-11-07 09:13:12,875 [INFO ] 34 introns registered...
2023-11-07 09:13:12,877 [INFO ] 22 mitochondrial tRNA sequences imported
2023-11-07 09:13:12,877 [INFO ] 611 filtered cytosolic tRNA sequences imported (Und, NNN and nmt sequences excluded)
2023-11-07 09:13:12,877 [INFO ] Processing modomics database...
2023-11-07 09:13:12,877 [WARNI] Retrieval of Modomics database disabled. Using local files instead...
2023-11-07 09:13:12,878 [INFO ] Parsing local Modomics data...
2023-11-07 09:13:12,880 [INFO ] Number of Modomics entries for Homo sapiens: 45
2023-11-07 09:13:12,880 [INFO ] Number of Modomics entries for Escherichia coli: 43
Traceback (most recent call last):
  File "/opt/homebrew/bin/mimseq", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mimseq/mimseq.py", line 418, in main
    mimseq(args.trnas, args.trnaout, args.name, args.species, args.out, args.cluster, args.cluster_id, args.cov_diff, \
  File "/opt/homebrew/lib/python3.11/site-packages/mimseq/mimseq.py", line 99, in mimseq
    = modsToSNPIndex(gtRNAdb = trnas, tRNAscan_out = trnaout, mitotRNAs = mito_trnas, plastidtRNAs = plastid_trnas, experiment_name = name, out_dir = out, double_cca = double_cca, threads = threads, snp_tolerance = snp_tolerance, cluster = cluster, cluster_id = cluster_id, posttrans_mod_off = posttrans, pretrnas = pretrnas, local_mod = local_mod)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mimseq/tRNAtools.py", line 396, in modsToSNPIndex
    aligntRNA(tempSeqs.name, out_dir, threads)
  File "/opt/homebrew/lib/python3.11/site-packages/mimseq/ssAlign.py", line 27, in aligntRNA
    subprocess.check_call(cmcommand, stdout = open(out + 'cm.log', 'w'))
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 408, in check_call
    retcode = call(*popenargs, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'cmalign'
```

**Comment by kelly-sovacool** [comment]
Also need to install BLAST and gmap. @drewjbeh are there any other dependencies (aside from usearch) that can't be handled by pip?

**Comment by drewjbeh** [comment]
There are a number of packages that can't be handled by pip, mainly the numerous R packages that mimseq needs. However, all of these including BLAST and infernal (which is where the `cmalign` command is from) can indeed be handled by conda/mamba. This is why there is this recommendation. 
I can update the README but the recommendation remains the same.

**Comment by drewjbeh** [comment]
There was also already a section listing and talking about dependency installation in the [docs](https://mim-trnaseq.readthedocs.io/en/latest/start.html#dependencies)

**Comment by kelly-sovacool** [comment]
Ah I missed that in the docs, thanks @drewjbeh!
