### ISSUE TITLE
Error During Final Deconvolution with Clustering Enabled for E. coli tRNA Analysis in MimSeq

### ISSUE THREAD

**Issue by AteeshaNegi** [nedialkova-lab/mim-tRNAseq#69]
I am trying to analyze the abundance, modification, and charging in tRNA of E. coli and mito tRNA of Human samples. When I use the following command for a human tRNA sample, the MimSeq code runs without any interruption. The command for MELAS sample:

`mimseq --species Hsap --threads 16 --control-condition 0_Control -n mimseq_Melas_test --out-dir ./mimseq_MELASE_YN --cluster --cluster-id 0.95 --min-cov 2000 --max-mismatches 0.1 --remap --remap-mismatches 0.075 MELAS_samples.txt`

However, when I use the same command for E. coli, I encounter an error during the final deconvolution step. The command used is:

`mimseq --species Ecol --threads 16 --control-condition EV_Control -n mimseq_A_bc1 --out-dir ./cluster_mimseq_A_bc1_test --cluster --cluster-id 0.95 --min-cov 2000 --max-mismatches 0.1 --remap --remap-mismatches 0.075 AlaGGC_A_bc1_test.txt > ./cluster_mimseq_output.logs
`

Error Log:
```

+-----------------------------------+         
| Final deconvolution and filtering |         
+-----------------------------------+
2024-08-03 12:25:48,458 [INFO ] 2 clusters filtered out according to minimum coverage threshold: 1000.0 total read coverage per isodecoder.
2024-08-03 12:25:49,374 [INFO ] Output final tables, counts and new mods...
2024-08-03 12:25:49,682 [INFO ] ** Read counts per anticodon saved to ./clusterID85_mimseq_A_bc1_test/counts/Anticodon_counts_raw.txt **
2024-08-03 12:25:49,682 [INFO ] ** Read counts per isodecoder saved to ./clusterID85_mimseq_A_bc1_test/counts/Isodecoder_counts_raw.txt **
2024-08-03 12:25:49,682 [INFO ] 2 sequences could not be deconvoluted as >10% parent assigned-reads do not match parent sequence!
2024-08-03 12:25:49,682 [INFO ] Reasons for this include misalignment of reads to an incorrect cluster, or inaccurate alignment by GSNAP (e.g. at indels in reads) prohibiting correct deconvolution.
2024-08-03 12:25:49,682 [INFO ] 2 total unique sequences not deconvoluted due to mismatches at modified sites, insufficient coverage or read mismatches to parent
Traceback (most recent call last):
  File "/home/hou_lab/miniforge3/envs/mimseq/bin/mimseq", line 8, in <module>
    sys.exit(main())
  File "/home/hou_lab/miniforge3/envs/mimseq/lib/python3.7/site-packages/mimseq/mimseq.py", line 421, in main
    args.misinc_thresh, args.mito, args.plastid, args.pretrnas, args.local_mod, args.p_adj, args.crosstalks, args.sampledata)
  File "/home/hou_lab/miniforge3/envs/mimseq/lib/python3.7/site-packages/mimseq/mimseq.py", line 165, in mimseq
    isodecoder_sizes = writeIsodecoderInfo(out, name, isodecoder_sizes,readRef_unsplit_newNames, tRNA_dict)
  File "/home/hou_lab/miniforge3/envs/mimseq/lib/python3.7/site-packages/mimseq/splitClusters.py", line 485, in writeIsodecoderInfo
    iso_min = min([x.split("-")[-1] for x in isodecoder_list])
ValueError: min() arg is an empty sequence
```
When I use the --no-cluster flag, I don't encounter this issue, but the alignment shows a high percentage of multi-mapping reads (Uniquely mapped reads: 48%; Multi-mapping reads: 48%).

With clustering, the uniquely mapped reads increase to 97%, but the run is interrupted and does not produce the final alignment folder, mod folder, or other output folders.

Questions:

1.     What might be causing this error during the final deconvolution step with clustering enabled for E. coli?
2.     Are there specific flags or parameters I should adjust to resolve this issue?
3.     What is the significance of clustering in terms of isodecoders (E. coli has very few isodecoders than human tRNA) and overall tRNA modification analysis in MimSeq?

Any insights or suggestions to resolve this would be greatly appreciated. Thank you!

PS: you can find the packages/ how mimseq was installed info in the link below:
https://github.com/conda-forge/miniforge/issues/621#issue-2446530656

**Comment by nedialkova-lab** [comment]
Hi there - can you try a cluster ID of 1? E.coli indeed has no isodecoders but it has multicopy tRNA genes; this should take care of multimapping coming from those.

**Comment by AteeshaNegi** [comment]
Thank you for the suggestion, it worked!
No error message this time.
