### ISSUE TITLE
mmQuant.py error

### ISSUE THREAD

**Issue by onuryukselen** [nedialkova-lab/mim-tRNAseq#7]
Hello,

I was running mimseq with custom mouse tRNA-seq data. Could you please check the error I got, what might me reason of it? 

Thanks very much for any advice.

This is the command I executed:
`mimseq -t /share/mm10/tRNAs-oligostd/tRNAs.fa -o /share/mm10/tRNAs-oligostd/tRNAs.out -m /share/mm10/tRNAs-oligostd/mitotRNAs.fa --cluster --cluster-id 0.95 --snp-tolerance --cca-analysis --threads 1 --min-cov 2000 --max-mismatches 0.1 --control-condition ctrl -n experiment4 --out-dir experiment4 --max-multi 1 --remap --remap-mismatches 0.075 groups.txt`

Logs:
2021-04-27 13:53:45,698 [INFO ] mim-tRNAseq v0.3.3 run with command:
2021-04-27 13:53:45,701 [INFO ]
+--------------------------------+
| Starting analysis for tRNAs.fa |
+--------------------------------+
2021-04-27 13:53:45,701 [INFO ] Processing tRNA sequences...
2021-04-27 13:53:45,756 [INFO ] 25 introns registered...
2021-04-27 13:53:45,773 [INFO ] 465 cytosolic and 22 mitochondrial tRNA sequences imported
2021-04-27 13:53:45,773 [INFO ] Processing modomics database...
2021-04-27 13:54:06,041 [INFO ] Modomics retrieved...
2021-04-27 13:54:06,042 [INFO ] Parsing Modomics JSON data...
2021-04-27 13:54:06,045 [INFO ] Number of Modomics entries for Mus musculus: 15
2021-04-27 13:54:06,045 [INFO ] Number of Modomics entries for Oligo standard-tRNA-Ala-TTG-1-1: 0
2021-04-27 13:54:06,045 [INFO ] Number of Modomics entries for Escherichia coli: 43
2021-04-27 13:54:06,045 [INFO ] Number of Modomics entries for suppressor tRNA: 0
2021-04-27 13:55:59,146 [INFO ]
....
....
....
+---------------------------------------------------------------------------------+        
| Determining un-deconvoluted clusters due to insufficient coverage at mismatches |        
+---------------------------------------------------------------------------------+
2021-04-27 16:18:59,706 [INFO ] *** Un-deconvoluted sequences being defined based on coverage difference more than 0.5
2021-04-27 16:18:59,707 [INFO ] Determining unsplittable sequences...
2021-04-27 16:18:59,719 [INFO ] Calculating nucleotide coverage for experiment4/Ctrl3.unpaired_uniq.bam
2021-04-27 16:20:15,281 [INFO ] Calculating nucleotide coverage for experiment4/Expr3.unpaired_uniq.bam
2021-04-27 16:21:41,058 [INFO ] 17 unique sequences excluded from deconvolution due to reductions in required coverage at mismatches of more than 50.00%
2021-04-27 16:21:41,059 [INFO ] 
+--------------------------------------------------------------------+		
| Analysing misincorporations and stops to RT, and analysing 3' ends |		
+--------------------------------------------------------------------+
2021-04-27 16:21:41,060 [WARNI] Rewriting over old mods and CCA files...
2021-04-27 16:21:41,258 [INFO ] Analysing experiment4/Ctrl3.unpaired_uniq.bam...
2021-04-27 16:34:02,762 [INFO ] Analysing experiment4/Expr3.unpaired_uniq.bam...
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/conda/envs/dolphinnext-trnaseq-1.0/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/opt/conda/envs/dolphinnext-trnaseq-1.0/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/opt/conda/envs/dolphinnext-trnaseq-1.0/lib/python3.7/site-packages/mimseq/mmQuant.py", line 240, in bamMods_mp
    for isodecoder, values in modTable.items()
  File "/opt/conda/envs/dolphinnext-trnaseq-1.0/lib/python3.7/site-packages/mimseq/mmQuant.py", line 240, in <dictcomp>
    for isodecoder, values in modTable.items()
  File "/opt/conda/envs/dolphinnext-trnaseq-1.0/lib/python3.7/site-packages/mimseq/mmQuant.py", line 238, in <dictcomp>
    for pos, data in values.items()
  File "/opt/conda/envs/dolphinnext-trnaseq-1.0/lib/python3.7/site-packages/mimseq/mmQuant.py", line 236, in <dictcomp>
    for group, count in data.items() if group in ['A','C','G','T']
ZeroDivisionError: division by zero
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/dolphinnext-trnaseq-1.0/bin/mimseq", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/envs/dolphinnext-trnaseq-1.0/lib/python3.7/site-packages/mimseq/mimseq.py", line 361, in main
    args.misinc_thresh, args.mito, args.pretrnas, args.local_mod, args.sampledata)
  File "/opt/conda/envs/dolphinnext-trnaseq-1.0/lib/python3.7/site-packages/mimseq/mimseq.py", line 135, in mimseq
    new_mods, new_Inosines, filtered_cov, filter_warning = generateModsTable(coverageData, out, name, threads, min_cov, mismatch_dict, insert_dict, del_dict, cluster_dict, cca, remap, misinc_thresh, new_mod_lists, Inosine_lists, newtRNA_dict, Inosine_clusters, unique_isodecoderMMs, newSplitBool, isodecoder_sizes, cluster)
  File "/opt/conda/envs/dolphinnext-trnaseq-1.0/lib/python3.7/site-packages/mimseq/mmQuant.py", line 596, in generateModsTable
    new_mods, new_Inosines = zip(*pool.map(func, bamlist))
  File "/opt/conda/envs/dolphinnext-trnaseq-1.0/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/opt/conda/envs/dolphinnext-trnaseq-1.0/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
ZeroDivisionError: division by zero

**Comment by drewjbeh** [comment]
Hi there,

Could you please start by upgrading to the newest mimseq package (v0.3.3.2) and trying again.
Also, what are the mapping rates like? Have a look at `mapping_stats.txt` and send the output here. 

It also looks like you're using a custom reference set of tRNA sequences - mimseq is quite sensitive to the format of these files. Particularly the fasta files with reference sequences. Please ensure the headers of these fasta have exactly the same format as those in the data mimseq is shipped with. From your log, I imagine these files are contained in `/opt/conda/envs/dolphinnext-trnaseq-1.0/lib/python3.7/site-packages/mimseq/data`. Have a look at the files in `mm10-eColitK/` as an example.

**Comment by onuryukselen** [comment]
I will test the new version, meanwhile please check the mapping_stats.txt at below:
Ctrl3.fastq
Uniquely mapped reads: 27362284 (70%)
Multi-mapping reads: 2630634 (7%)
Unmapped reads: 8908186 (23%)
Total: 38901104

Expr3.fastq
Uniquely mapped reads: 29541678 (70%)
Multi-mapping reads: 2929147 (7%)
Unmapped reads: 9919716 (23%)
Total: 42390541

** NEW ALIGNMENT **

Ctrl3.fastq
Uniquely mapped reads: 28111466 (72%)
Multi-mapping reads: 2837336 (7%)
Unmapped reads: 7952302 (20%)
Total: 38901104

** NEW ALIGNMENT **

Expr3.fastq
Uniquely mapped reads: 30506752 (72%)
Multi-mapping reads: 3140766 (7%)
Unmapped reads: 8743023 (21%)
Total: 42390541

Also input files that I entered as a reference are listed below:
https://galaxyweb.umassmed.edu/pub/dnext_data/genome_data_other/mim-tRNAseq/mouse/mm10/tRNAs-eColitK-suppressor-oligostd/mitotRNAs.fa
https://galaxyweb.umassmed.edu/pub/dnext_data/genome_data_other/mim-tRNAseq/mouse/mm10/tRNAs-eColitK-suppressor-oligostd/tRNAs.fa
https://galaxyweb.umassmed.edu/pub/dnext_data/genome_data_other/mim-tRNAseq/mouse/mm10/tRNAs-eColitK-suppressor-oligostd/tRNAs.out

Please let me know if something is not right.
Thanks.

**Comment by onuryukselen** [comment]
I checked the new version, unfortunately the error is the same. Do you need any intermediate files to debug the run?
Thanks a lot.

**Comment by drewjbeh** [comment]
Hi,
Thanks for the update. I will try to do a test run with your references and some mouse data we have, but obviously this debugging will be a lot more applicable with the data you are using. Of course I understand if you can't or don't want to share that data here, but if not it would be great to get it from you (or at least a subset) to try and recreate your problem so I can go from there.
For now, could you try using the prepackaged mouse reference data that comes with mimseq instead of your custom inputs? Just remove the `-t`, `-o` and `-m` parameters and replace with `--species Mmus`. That will at leat identify your files as the problem or rule them out.

**Comment by drewjbeh** [comment]
So, the run completed with your references on our mouse data. Seems to be something specific to your libraries. Its pretty tough for me to troubleshoot this without being able to replicate the issue though. Let me know if sharing your data is possible!

**Comment by onuryukselen** [comment]
Hi Thanks a lot, please find files that I used:
https://galaxyweb.umassmed.edu/pub/dnext_data/test/Ctrl3.fastq
https://galaxyweb.umassmed.edu/pub/dnext_data/test/Expr3.fastq

Best,
Onur

**Comment by drewjbeh** [comment]
Hi, thanks for sharing!
Good news - I found the problem and wrote some new code to catch that `ZeroDivisionError` exception. 
I also fixed a few other errors and added some new plots and functionality (see https://github.com/nedialkova-lab/mim-tRNAseq/releases). 
This version (v0.3.4) will hopefully be available for upgrade via bioconda in the next few days. 
I tested your data and got a complete run (and it looked pretty good!), I would be interested to hear if you can get the same result with the new version.

**Comment by onuryukselen** [comment]
Hi, thanks a lot for your quick fix. I will try and let you know about how it works.

**Comment by drewjbeh** [comment]
Hi there - v0.3.4 is now available on bioconda. Let me know if this helps!

**Comment by onuryukselen** [comment]
Thanks a lot for your help, It worked smoothly. I'm closing the issue.
