### ISSUE TITLE
problem with final deconvolution-cov

### ISSUE THREAD

**Issue by zhouuplus** [nedialkova-lab/mim-tRNAseq#74]
hi, i 

2024-10-23 20:51:38,372 [WARNI] 70% or more clusters filtered out by --min-cov: consider reducing or assessing data quality and depth!
Traceback (most recent call last):
  File "/home_data/home/slst/zhouyj2022/anaconda3/envs/trna/bin/mimseq", line 10, in <module>
    sys.exit(main())
  File "/home_data/home/slst/zhouyj2022/anaconda3/envs/trna/lib/python3.7/site-packages/mimseq/mimseq.py", line 421, in main
    args.misinc_thresh, args.mito, args.plastid, args.pretrnas, args.local_mod, args.p_adj, args.crosstalks, args.sampledata)
  File "/home_data/home/slst/zhouyj2022/anaconda3/envs/trna/lib/python3.7/site-packages/mimseq/mimseq.py", line 153, in mimseq
    new_mods, new_Inosines, filtered_cov, filter_warning, unsplitCluster_lookup,readRef_unsplit_newNames = generateModsTable(coverageData, out, name, threads, min_cov, mismatch_dict, insert_dict, del_dict, cluster_dict, cca, remap, misinc_thresh, new_mod_lists, Inosine_lists, newtRNA_dict, Inosine_clusters, unique_isodecoderMMs_new, splitBool_new, isodecoder_sizes, unsplitCluster_lookup, cluster, crosstalks)
  File "/home_data/home/slst/zhouyj2022/anaconda3/envs/trna/lib/python3.7/site-packages/mimseq/mmQuant.py", line 811, in generateModsTable
    newProps = modTable.loc[(modTable.isodecoder.isin(readRef_unsplit_newNames))].groupby(["isodecoder","canon_pos","pos","type","condition","bam"]).agg(cov=("cov", "sum"), proportion=("proportion", wm)).reset_index()[["isodecoder", "canon_pos", "pos", "type", "proportion", "cov", "condition", "bam"]]
  File "/home_data/home/slst/zhouyj2022/anaconda3/envs/trna/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 979, in aggregate
    result = op.agg()
  File "/home_data/home/slst/zhouyj2022/anaconda3/envs/trna/lib/python3.7/site-packages/pandas/core/apply.py", line 161, in agg
    return self.agg_dict_like()
  File "/home_data/home/slst/zhouyj2022/anaconda3/envs/trna/lib/python3.7/site-packages/pandas/core/apply.py", line 436, in agg_dict_like
    key: obj._gotitem(key, ndim=1).agg(how) for key, how in arg.items()
  File "/home_data/home/slst/zhouyj2022/anaconda3/envs/trna/lib/python3.7/site-packages/pandas/core/apply.py", line 436, in <dictcomp>
    key: obj._gotitem(key, ndim=1).agg(how) for key, how in arg.items()
  File "/home_data/home/slst/zhouyj2022/anaconda3/envs/trna/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 249, in aggregate
    ret = self._aggregate_multiple_funcs(func)
  File "/home_data/home/slst/zhouyj2022/anaconda3/envs/trna/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 303, in _aggregate_multiple_funcs
    results[key] = self.aggregate(func)
  File "/home_data/home/slst/zhouyj2022/anaconda3/envs/trna/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 262, in aggregate
    return self._python_agg_general(func, *args, **kwargs)
  File "/home_data/home/slst/zhouyj2022/anaconda3/envs/trna/lib/python3.7/site-packages/pandas/core/groupby/groupby.py", line 1332, in _python_agg_general
    result = self.grouper.agg_series(obj, f)
  File "/home_data/home/slst/zhouyj2022/anaconda3/envs/trna/lib/python3.7/site-packages/pandas/core/groupby/ops.py", line 1060, in agg_series
    result = self._aggregate_series_fast(obj, func)
  File "/home_data/home/slst/zhouyj2022/anaconda3/envs/trna/lib/python3.7/site-packages/pandas/core/groupby/ops.py", line 1085, in _aggregate_series_fast
    result, _ = sgrouper.get_result()
  File "pandas/_libs/reduction.pyx", line 281, in pandas._libs.reduction.SeriesGrouper.get_result
  File "pandas/_libs/reduction.pyx", line 88, in pandas._libs.reduction._BaseGrouper._apply_to_group
  File "/home_data/home/slst/zhouyj2022/anaconda3/envs/trna/lib/python3.7/site-packages/pandas/core/groupby/groupby.py", line 1318, in <lambda>
    f = lambda x: func(x, *args, **kwargs)
  File "/home_data/home/slst/zhouyj2022/anaconda3/envs/trna/lib/python3.7/site-packages/mimseq/mmQuant.py", line 810, in <lambda>
    wm = lambda x: np.average(x, weights=modTable.loc[x.index, "cov"])
  File "<__array_function__ internals>", line 6, in average
  File "/home_data/home/slst/zhouyj2022/anaconda3/envs/trna/lib/python3.7/site-packages/numpy/lib/function_base.py", line 410, in average
    "Weights sum to zero, can't be normalized")
ZeroDivisionError: Weights sum to zero, can't be normalized

**Comment by zhouuplus** [comment]
hi i recently run into some problem in Final deconvolution and filtering. i run with the command like this: 
"mimseq --species Mmus --cluster-id 0.95 --threads 15 --min-cov 0.00001 --max-mismatches 0.1 -n enbryo --out-dir 20241023_3 --max-multi 4 --remap --remap-mismatches 0.05 tRNA.txt --control-condition WT" 

the mapping stats looks fine, for example
"L15-1_L1_1_trimmed_trimmed_trimmed.fq
Uniquely mapped reads: 808604 (28%) 
Multi-mapping reads: 6024 (0%) 
Unmapped reads: 2061006 (72%) 
Total: 2875634

L15-2_L5_1_trimmed_val_1.fq
Uniquely mapped reads: 865179 (21%) 
Multi-mapping reads: 11065 (0%) 
Unmapped reads: 3232359 (79%) 
Total: 4108603
"
i dont think it is problem with min-cov parameter as i run mimseq on lower mapping rate data, do you have any suggestions?
i am using mimseq v1.3.8, thank you!

**Comment by drewjbeh** [comment]
Hi there,

The error is coming from a weight matrix calculation to report proportion of mismatches in mismatchTable.csv. This weight matrix takes into account the coverage at each position to calculate the denominator for proportion calculation. The error that these weights sum to 0 probably comes from bad coverage at one or more positions and this is related to your alignment data. You say "the mapping stats look fine" but honestly in our experience 28% uniquely mapped reads is very poor. We would advise to do some QC on your library prep and ensure that your samples are of high quality so that this number goes up. This should help with many issues.
